# Abstract {.unnumbered header-title="Abstract"}

This thesis synthesises three complementary studies to unravel the macroevolutionary dynamics of South American land mammal fauna across the Cenozoic (last 66 million years), through quantitative analyses of the fossil record, dated phylogenies and eco-evolutionary simulations. In a first chapter, the impact of the Eocene--Oligocene Transition (EOT, the most dramatic climatic crisis of the Cenozoic), on the endemic South American mammal faunas is evaluated using of cutting-edge diversification inference frameworks based on fossil occurrences. Our findings challenge the status of mass extinction of the EOT in South America. Instead, we evidence a gradual diversity decline from the middle Eocene to the early Oligocene, encompassing a pronounced a taxonomic (but not ecological) turnover. Temperature changes, diversity-dependent effects, and the Andean uplift emerged as primary drivers behind the reconstructed diversification patters. Also, our findings evidenced that tropical lineages maintained stable diversification rates, supporting the cornerstone *Tropical stability* hypothesis formulated by Wallace. In a second chapter, we focus on a poorly-diverse extant caviomorph rodent clade, the Chinchilloidea. The fossil record suggests that this clade used to be much more diverse in the past, and notably accounted for the largest rodents ever recorded. By integrating fossil occurrences, molecular phylogenies, and trait reconstructions derived from cranio-dental measurements, this study reveals that chinchilloid decline was driven by a shift in extinction regimes during the Late Miocene. This extinction pulse was selective, disproportionately affecting large-bodied, extratropical taxa, and was likely mediated by the Andean uplift and sea-level changes, factors that were shown to be responsible for the collapse of large Miocene wetlands. Our findings highlight the scale-dependent relationship between taxonomic diversity and body mass disparity, illustrating how traits synergise with environmental factors to fashion the fate of the clades. Finally, Chapter 3 addresses the Great American Biotic Interchange (GABI), the Pliocene faunal exchange between North and South America that was heavily biased towards North American lineages. Using mechanistic eco-evolutionary simulations coupled with palaeoclimate data, this study tests whether palaeoclimate dynamics alone can explain this asymmetry, a long-standing hypothesis. When climate is the sole constraint to virtual species dispersal, our simulations fail to reproduce the empirical pattern of exchange asymmetry, even favouring South-to-North movement. With most exchanges occurring within the tropical biome, our models fail to reproduce the over-representation of temperate specialists in the fossil record of successful migrants. These findings ultimately suggest that additional factors must have been at play to shape this macroecological enigma. Collectively, these studies underscore the uniqueness of South American evolutionary trajectories, emphasising the critical role of regional idiosyncrasies, tectonic events, and traits in the evolutionary history of mammal species in the most mammal-rich regions of the world.

{{< pagebreak >}}

# Résumé {.unnumbered header-title="Résumé"}

Cette thèse synthétise trois études complémentaires décryptant les dynamiques macroévolutives des mammifères terrestres sud-américains au cours du Cénozoïque (*i*.*e*., 66 derniers millions d'années), grâce à des analyses quantitatives du registre fossile, de phylogénies datées et de simulations éco-évolutives. Dans un premier chapitre, l'impact de la Transition Éocène-Oligocène (EOT, la crise climatique la plus dramatique du Cénozoïque) sur les faunes mammaliennes endémiques d'Amérique du Sud est évalué en utilisant des méthodes d'inférence de diversification à la pointe basées sur des occurrences fossiles. Nos résultats remettent en question le statut d'extinction de masse de l'EOT en Amérique du Sud. Nous mettons plutôt en évidence un déclin graduel de la diversité du milieu de l'Éocène au début de l'Oligocène, englobant un renouvellement taxonomique (mais non-écologique) prononcé. Nos analyses suggèrent que les changements de température, la diversité-dépendance et le soulèvement des Andes seraient les principaux facteurs ayant façonné les dynamiques de diversification des mammifères au cours de la période d'étude. De plus, nos résultats soutiennent l'hypothèse phare de 'stabilité tropicale' formulée par Wallace, selon laquelle les groupes tropicaux auraient des variations de taux de diversification moins marquées que ceux vivant à l'extérieur des tropiques. Dans un deuxième chapitre, nous nous sommes centrés sur un clade de rongeurs caviomorphes actuellement peu diversifié, les chinchilloïdes. Leur registre fossile suggère que ce clade était beaucoup plus diversifié dans le passé, et incluait notamment les plus grands rongeurs jamais enregistrés. En intégrant des occurrences fossiles, une phylogénie moléculaire datée et des reconstructions de traits issues de mesures cranio-dentaires, cette étude révèle que le déclin des chinchilloïdes est dû à un changement de régime d'extinction au Miocène tardif. Nos résultats illustrent la sélectivité de cette hausse d'extinction, affectant de manière disproportionnée les taxons de grande taille et extratropicaux. Nos analyses révèlent que les facteurs à l'origine de ce changement de taux d'extinction sont le soulèvement des Andes et les variations eustatiques, des facteurs impliqués dans l'effondrement des zones humides du Miocène. Ces résultats soulignent également que la relation entre diversité taxonomique et disparité de masse corporelle dépend de l'échelle phylogénétique. Enfin, le dernier chapitre de ce manuscrit aborde le Grand Échange Biotique inter-Américain (GABI), l'échange faunistique ayant eu lieu au Pliocène entre l'Amérique du Nord et l'Amérique du Sud, fortement biaisé en faveur des lignées nord-américaines. En utilisant des simulations éco-évolutives mécanistiques couplées à des données paléoclimatiques de haute résolution, nous testons l'hypothèse de longue date selon laquelle l'asymétrie du GABI aurait émergé à partir des fluctuations paléoclimatiques du Plio-Pleistocène. Lorsque le climat est la seule contrainte à la dispersion des espèces simulées, nos modèles ne parviennent pas à reproduire l'asymétrie d'échange empirique, favorisant même une asymétrie oposée, *càd* du Sud vers le Nord. Nos analyses illustrent également que la plupart des échanges ont eu lieu au sein du biome tropical, échouant alors à reproduire la sur-représentation d'espèces inféodées à des milieux ouverts dans le registre fossile des migrants. Ces résultats suggèrent en fin de compte que d'autres facteurs ont dû entrer en jeu pour façonner l'énigme macroécologique que constitue l'asymétrie du GABI. Collectivement, ces études soulignent l'unicité des trajectoires évolutives sud-américaines, en mettant en évidence le rôle critique des idiosyncrasies régionales, des événements tectoniques et des traits dans l'histoire évolutive des mammifères peuplant la région la plus riches en mammifères au monde.


{{< pagebreak >}}

```{=latex}
\includepdf[pages=-, scale=1]{./Fioritures/resume_FR.pdf}
```
