# Chapter 1. The fate of South America's endemic mammalian fauna in response to the most dramatic Cenozoic climate disruption

::: {.content-visible unless-format="pdf"}
## Foreword

Understanding what drove the emergence and demise of lineages during biodiversity crises may provide key insights at the time of the sixth mass extinction. Here, using a vetted fossil database, we explored how South American mammals (SAM) responded to the most dramatic Cenozoic climate cooling episode, the Eocene−Oligocene transition (ca. 34 Ma). We found that SAM experienced a gradual and long-standing diversity decline strongly related to late Eocene progressive climate cooling, followed by a major taxonomic turnover in the Oligocene, driven by diversity-dependent factors, Andean uplift and perhaps grassland expansion. SAM were therefore more subject to long-term diversity changes rather than abrupt ones, contrary to what would be expected in a mass extinction scenario.

The content of this chapter was published in PNAS [@buffan2025].

## Abstract

Around 34 million years ago (Ma), the Eocene−Oligocene transition (EOT) marked the most dramatic global climatic cooling of the Cenozoic. On a planetary scale, paleontological evidence suggests that this transition was associated with major faunal turnovers, sometimes even regarded as a mass extinction crisis. In South America, there is no consensus on the response of the endemic mammals to this transition. Here, using a vetted fossil dataset and cutting-edge Bayesian methods, we analyzed the dynamics of South American mammal (SAM) diversification and their possible drivers across latitude (tropical vs. extratropical), taxonomic groups, and trophic guilds throughout the Eocene−Oligocene (ca. 56−23 Ma). Our results did not evidence any mass extinction among SAM at the EOT. Instead, they experienced a gradual and long-term diversity decline from the middle Eocene to the early Oligocene, followed by a sudden waxing-and-waning diversity associated with a large taxonomic -- but not ecological -- turnover. Tropical and extratropical lineages have had very distinct macroevolutionary histories. No effective change in the pace at which tropical lineages diversify was found, thus favoring the tropical stability hypothesis proposed by Wallace. Diversity-dependent effects, temperature and Andean uplift were recovered as probable drivers of SAM diversification across the period. Contrasting evidence casts doubt on the common hypothesis primarily linking Oligocene faunal changes to grassland expansion. Our findings illustrate the uniqueness of the deep-time interplay between endemic SAM and their physical environment in a context of climatic shift, highlighting the need to consider regional idiosyncrasies for understanding the coevolution of life and climate.

## Introduction

Today, South America is home to a unique mammalian fauna, hosting one of the most species-rich regions of the world, Amazonia [@willig2003]. Although the extant mammalian taxonomic diversity in the continent is astonishing, it is a poor reflection of what can be drawn from the fossil record. In fact, throughout most of the Cenozoic (i.e., the last 66 million years), South America was isolated from other landmasses [@scotese_atlas_2021]. In this insular context, terrestrial mammal lineages that inhabited this huge landmass experienced unique radiations [@goin2016; @boivin2019; @croft2020; @beck2023; @tejada2024]. According to @simpson1980 , South American mammal (SAM) communities through the Cenozoic are well summarized by three successive ‘faunal strata’. The first one, stretching from the early Paleocene (66 million years ago, Ma) to the late Eocene (ca. 37 Ma), is characterized by the early establishment and radiation of endemic lineages, mostly xenarthrans, metatherians and native ungulates. Then, from the early Oligocene (ca. 33 Ma) until the Late Miocene-Early Pliocene (ca. 5 Ma), key morphological innovations appeared among native lineages, leading to a so-called ‘faunal modernization’ [@croft2008]. In the meantime, rodents and primates, Afro-Asian lineages that most likely reached South America in the middle-late Eocene [@antoine2012; @bond2015; @marivaux2023], diversified locally [@boivin2019; @beck2023]. In Plio-Pleistocene times, this endemic fauna was massively disrupted. Meanwhile, the closure of the Panama isthmus [@montes2015] had paved the way for major faunal exchanges between North and South America, described as the ‘Great American Biotic Interchange’ [@marshall1988], and immigrant taxa from North America (*e*.*g*., carnivores, perissodactyls, artiodactyls, or proboscideans) appeared in the South American fossil record. In the last millions of years, many endemic South American lineages declined, or even went totally extinct (e.g., litopterns, notoungulates, sparassodonts, glyptodonts, ground sloths).

Close to the limit between Simpson’s first and second faunal strata, the Eocene−Oligocene transition (EOT, *ca*. 33.9 Ma) marked the most dramatic Cenozoic climatic change episode worldwide [@coxall2007]. At that time, simultaneously, global climate massively cooled down [@westerhold2020], ocean level dropped [@miller2020], and the whole Antarctic continent turned into a giant ice sheet [@liu2009]. The prevailing mechanism proposed to explain these major environmental changes is the onset of the Antarctic circumpolar current [@toumoulin2020]. Concomitantly, a major biotic turnover among mammals, known as the '*Grande Coupure*', occurred in Europe [@stehlin1909]. This event, punctuated by the arrival of immigrant taxa from Asia, saw the demise of many endemic European lineages [@legendre1991; @escarguel2008; @weppe2023]. Although European-oriented case studies dominate the literature about the topic, similar disruptions among mammalian faunas occurred at the same time in other regions of the world, such as Asia [@meng1998; @kraatz2010; @sun_synchronous_2014], North America [@figueirido2012; @stucky2014], Africa [@devries2021] or to some extent Madagascar [@godfrey2020]. Recently, @hoyalcuthill2020 even came to rank this geological boundary as the second-most important extinction event throughout the history of life.

In central and southern South America, substantial changes have been documented in metatherians [@abello2020; @goin2010] and native ungulates [@croft2020; @solórzano2024] near the EOT. As an echo to the '*Grande Coupure*', @goin2010 even introduced the term '*Bisagra Patagónica*' (Patagonian Hinge) to characterize the changes among metatherian communities in Patagonia possibly related to the EOT. General morphological trends have been highlighted in 'modernised' notoungulate faunas, with a net increase in body mass and cheek teeth’s crown height [@solórzano2021]. The latter changes, by analogy with the evolutionary fate of extant groups, suggested the emergence of the grazing feeding mode, and was postulated to result from the expansion of grasslands, promoted by post-EOT climate cooling and aridification [@solórzano2024; @stebbins1981; @reguero2010]. In northern South America, changes in methaterian and rodent communities around the EOT have also been suggested despite the paucity of known Palaeogene low-latitude fossil localities to date [@antoine2021]. Additionally, geological, paleontological and phylogenetic evidence suggests that the Eocene−Oligocene was a key interval for the dispersal of SAM toward Caribbean Islands, further playing a central role in the architecture of these unique insular ecosystems [@tejada2024; @philippon2020; @cornée2021; @marivaux_early_2020].

Despite general agreement that a faunal remodelling occurred in SAM communities near the EOT, the evolutionary tempo and mode remain unknown. At macroevolutionary scales, as we would expect in a mass extinction scenario (*SI Appendix*, *Supplementary text*), it is unclear whether this faunal renewal was characterized by extinction of Eocene lineages followed by diversification of the surviving ones [@guinot2023], or whether lineages gradually transitioned until they became 'modernised'. A crucial question underlying these conflicting macroevolutionary hypotheses is whether or not extinction occurred in the tropics, and at what level. Indeed, it has long been postulated that the climatic stability of tropics would make tropical lineages less vulnerable to extinction than extratropical lineages [@wallace1878]. Also, the ecological selectivity and the likely drivers of this apparent faunal transition have remained underexplored. For instance, there is currently no consensus regarding the role of temperature [@kohn2004; @kohn2015] or grassland expansion [@strömberg2013] in shaping the macroevolutionary fate of SAM. Finally, there is a lack of integrative frameworks at the continental scale, with most case studies at the local scale, mostly in southern South America. Nevertheless, the Palaeogene mammal fossil record in South America is spatially and temporally uneven. Spatial gaps cover large areas, such as most of the Amazon basin, and important time intervals have remained unsampled to date (*SI Appendix*, *Fig. S1* and *S3*). Accordingly, it has been historically challenging to address questions regarding the history of SAM at the continental scale.

Here, we aim to fill these gaps by examining the available fossil record of SAM. We assembled a genus-level fossil dataset consisting of 3,378 occurrences (distributed in 1,115 species, 536 genera, 96 families, and 18 orders) spanning from the late Paleocene to the Early Miocene. Relying on a fossil-based Bayesian birth-death framework accounting for variable preservation rates through time and across taxa [@silvestro_bayesian_2014], we estimated the tempo and modes of the mammalian diversification dynamics in South America throughout the Eocene--Oligocene interval (*ca*. 56--23 Ma). We then disentangled the underlying taxonomic, functional, and geographic (tropical vs. extratropical) bases of the inferred continent-scale patterns of diversity and diversification among SAM faunas. We finally quantified the most likely biotic and abiotic drivers explaining their diversification dynamics.

## Results and discussion

### No mass extinction: South American mammal diversity gradually declined well before the EOT

We analyzed the fossil database (Tab. S1) both at the genus and species levels using the process-based Bayesian framework of diversification accounting for varying preservation implemented in PyRate [@silvestro_bayesian_2014]. Our results highlight that the overall mammal diversity gradually declined from the end of the early Eocene -- shortly after the Early Eocene Climate Optimum (EECO, 45) -- to the end of the early Oligocene (decline by respectively 34% and 52% in the number of genera and species between 48 and 32 Ma), and then further increased in the late Oligocene (Fig. 1D and SI Appendix, Fig. S8-11). No massive loss of lineages was evidenced at the EOT. This diversity trajectory results from a significant decrease in origination rate during the early Eocene (Fig. 1B and SI Appendix, Fig. S8-11). Additionally, we recover a joint significant increase in the pace of origination and extinction (i.e., increased turnover) during the late Eocene, with the extinction rate always being higher than the origination rate (slightly negative net diversification rate; Fig. 1B-C and SI Appendix, S8-11). Similar diversification patterns are recovered when analyzing the dataset at the genus or species level (SI Appendix, Fig. S8-11), after removing singletons (SI Appendix, Fig. S12-13) or disabling several occurrences of the same lineage that co-occur temporally and geographically (SI Appendix, Fig. S14-15). Moreover, general trends in diversity and diversification dynamics are conserved when working with occurrences assigned to South American Land Mammal Ages (SALMAs; SI Appendix, Fig. S9 and S11) instead of sub-epochs (see Methods; SI Appendix, Fig. S1-2 and Extended Material and Methods), or when considering attempts to derive early Oligocene ages to western Amazonian occurrences originally assigned to an Eocene age (SI Appendix, Fig. S32).

```{r, echo=FALSE}
#| label: fig-DivRTT
#| out-height: 20cm
#| fig-cap: Bayesian reconstructions of taxon longevities (**A**), diversification (**B**-**C**) and diversity (**D**) dynamics of South American Mammals from the early Eocene to the late Oligocene (genus level). The plot on the left (**A**) shows the longevity -- i.e., interval between origination and extinction times -- of each Eocene--Oligocene (373 out of 529 genera) South American mammal genus estimated with PyRate. J- and F-values respectively represent Jaccard’s and Forbes’ similarity indices computed between Eocene and Oligocene assemblages for each of the five groups. The right part of the panel shows the origination (blue) and extinction (red) rates through time (**B**), the net diversification rate (origination minus extinction) (**C**), and diversity (**D**) of all South American mammals throughout the study period. Full lines represent median estimates and ribbons their associated 95% higher posterior density. Light brown vertical bands indicate two key climate events, the Early Eocene Climate Optimum (EECO, ~53--51 Ma) and the Middle Eocene Climate Optimum (MECO, ~41.5--41 Ma). Stars on the (**B**) plot indicate significant rate shifts. Organisms’ silhouettes are from PhyloPic (https://www.phylopic.org) and were added thanks to the R package rphylopic (98). Silhouettes were contributed by Julián Bayona, 2016 (CC BY-SA 3.0), Milena Cavalcanti, Patricia Pilatti & Diego Astúa (CC BY 4.0). Geological and South American Land Mammal Ages (SALMA) timescales were depicted thanks to the deeptime R package (99). Abbreviations for SALMA. Des: Deseadan, Ting: Tinguirirican, Must: Mustersan, Bar: Barrancan, Sap: “Sapoan Fauna”, R: Riochican, It: Itaboraian. The small band between Tinguirirican and Deseadan is the “La Cantera fauna”.

```


{{< pagebreak >}}
:::
