# General Discussion {header-title="General Discussion"}

Over this thesis, several aspects of the evolution of South American mammals across the Cenozoic have been explored, using a diverse array of data and quantitative methods.

First, attention has been dedicated to the extent to which Palaeogene South American mammalian assemblages have been affected by the vast climatic disruption that occurred near the Eocene--Oligocene Transition (EOT, *ca*. 33.9 Ma). This geological boundary was indeed associated with significant waves of extinctions in the land mammalian faunas of the Northern Hemisphere. In South America, despite some considerations that a faunal turnover did occur near the EOT based on regional-scale qualitative observations from patagonian localities, until this thesis, no quantitative assessment of the status of the EOT at the continent-scale had ever been conducted in the framework of land mammals -- or, actually, any other taxonomic group. To this end, an unprecedented genus-level fossil occurrence dataset was assembled. This dataset was analysed using a Bayesian occurrence-based framework for diversification inference. Surprisingly, these analyses did not retrieve a strong extinction signal at the Eocene--Oligocene boundary. Rather, a gradual decrease in diversity was recovered during most of the Eocene, following the long-term climate cooling that operated from the Early Eocene climate optimum onwards. A significant turnover was however detected, but largely predating the EOT. A sustained positive relationship between the Andean uplift and South American mammal extinction rate was also evidenced over the study period, together with diversity-dependent effects. Finally, tropical and extratropical faunas were found to be tied to distinct evolutionary regimes, notably, with an absence of rate variation in the tropics. Overall, these findings suggest that the mass extinction status of the EOT from a global perspective should be reconsidered. Also, the findings produced over this study provided support for the long-standing 'Tropical Stability' hypothesis, stemming from the thought of A. R. Wallace in the late XIX century, thus contributing to the understanding of the evolution of the unique tropical diversity.

In a second chapter, some efforts were devoted to elucidate the evolutionary history of an endemic group of South American rodents that underwent a recent decline in taxonomic diversity, namely, the Chinchilloidea (Hystricognathi:Caviomorpha). This charismatic rodent superfamily today accounts for eight species, but its fossil record documents a much larger diversity in the past -- notably encompassing the largest rodents ever recorded, weighting up to 300 kg. The causes behind chinchilloid evolutionary decline remain uncertain, and despite several proposed hypotheses, have never been properely quantified. By means of an outstanding temporal occurrence dataset synthesising palaeontological and neontological data for 124 extinct and extant species and cutting-edge trait- and environment-dependent diversification methodologies, the macroevolutionary dynamics of Chinchilloidea were reconstructed. It stood out that chinchilloid diversification was best summarised by a birth--death model with constant speciation and time-variable extinction, the latter markedly increasing in the Late Miocene. This shift in extinction rate was selective against large-sized and extratropical taxa. A prominent role of the Andean uplift and eustatic variations was highlighted in shaping chinchilloid extinction rate, possibly suggesting an implication of the Late Miocene vanishing of large South American wetlands in the demise of this clade. Additionally, this work highlights several caveats related to input data while conducting occurrence-based macroevolutionary analyses, and discusses the crucial need to embrace uncertainty.

In a final chapter, emphasis was placed on the asymmetry behind the Great American Biotic Interchange (GABI), a vastly enigmatic feature of this inter-american faunal exchange, in which North American taxa were undoubtedly more successful at colonising the South than the other way around. Using eco-evolutionary simulations coupled with high-resolution palaeoclimate reconstructions covering the last five million years, the contribution of palaeoclimate, often proposed as a major driver behind such an asymmetry, was mechanistically tested. These simulations failed to reproduce the empirical pattern of exchange asymmetry. When climate was the only factor constraining virtual species' niche, across 500-member simulations either starting from North or South America, more South-to-North than North-to-South exchanges were obtained, mostly within the tropical biome. This finding interestingly suggests that, beyond climate, additional factors must have been at play to shape the striking imbalance behind the GABI. Over this chapter, the strengths of using a simulation approach to investigate the mechanisms underlying the emergence and the dynamics of biodiversity patterns are also discussed, notably as a means to circumvent the intrinsic biases of the fossil record.

## A deep-time perspective on the Cenozoic history of South American mammals

### On the macroevolutionary status of the tropics

Cradle vs. museum debate

Sampling issues

'Holding pen'?

### On the status of the Eocene--Oligocene boundary

EOT: A mass extinction? Could this, as proposed by @bambach2006, reflect the fact that the definition of a mass extinction should incorporate degrees of freedom?

Regional idiosyncrasies

### An almost closed system: founding migrations in the Palaeogene history of South American mammals {#sec-Mig}

As seen in @sec-SAFauna, South America's 'Splendid Isolation' was disrupted by the arrival of anthropoid primates and hystricognathous rodents, some time in the middle--late Eocene (@fig-SALMA). These lineages are today represented by two endemic South American radiations: Platyrrhini (flat-nosed primates) and Caviomorpha (new-world hystricognaths). The origin of these lineages has been much debated in the palaeontological community, some believing these 

Hystricognathous rodents & platyrrhine primates. Introduce the debate. We lack fossil evidence for the earliest comers, oldest occurrences in Western Amazonia whereas most likely come from Afro-Asian ancestors, so should have arrived by the East. Polyphyletic/several crossing events? Summarised in @marivaux2023

Refer to @simpson1950

A recent quantitative study suggested that the diversification of rodents and primates negatively affected the diversity of the endemic groups [@pino2025].

There is still some work to do to accurately elucidate continent-scale macroevolutionary dynamics of Caviomorph rodents (others than Chinchilloids, a contribution of this thesis): set the scene for GIGARAT[^discu-1]

[^discu-1]: The perspectives developed here have been formalised in a post-doctoral proposal submitted to an organisation attached to the University of Montpellier in January this year. I was informally told that this project has not even been considered by the jury, who favoured applications from outside the University -- which was nowhere indicated in the submission guidelines. *Oui, j'ai le seum*.

### If climate didn't, what drove the asymmetry of the GABI?

The findings produced over \textcolor{Blue}{Chapter 3} indicate that the asymmetry of the GABI cannot be viewed as a sole consequence of palaeoclimate dynamics, thus offering little support to the climate-driven asymmetry hypotheses (@fig-hypotheses). This therefore leaves the mystery of the forces behind the asymmetry of the GABI entirely open; if climate cannot be mechanistically regarded as such, what may have caused this biogeographic imbalance?

Acknowledging that "the ultimate factors [behind the asymmetry of the GABI] have not been and probably cannot be designated", @simpson1950 proposed that the asymmetry of the GABI arose as a consequence of an inter-continental imbalance in exposure to external competitive pressures, shaped by the distinct biogeographic histories of the two continents. According to him, the fact that intermittent connections between North America and Eurasia emerged during the Neogene imposed a "series of competitive episodes" involving mammal lineages of these two continents. As a result, at the onset of the GABI, North American mammal faunas would have been exclusively composed of competitively "successful" lineages. On the other hand, South American mammalian faunas had evolved in a vacuum over most of the Cenozoic (@sec-SAFauna), almost without being exposed to any sort of competitive pressure exerted by a foreign lineage (but see @sec-Mig). Competition has therefore been a long-standing paradigm to explain the asymmetry of the GABI. Recent evidence from stable isotopes suggested that North American lineages occupying different trophic levels (primary or higher consumers) had broader niches than South American lineages, which could have spurred their successful settlement in South America [@domingo2020]. On the other hand, the competitive exclusion hypothesis was intensively examined in the Sparassodonta, an emblematic South American metatherian predator clade, often assumed to have been outcompeted by North American carnivores as these migrated to the South, and evidence from quantitative analyses of their fossil record challenged the role of clade competition in underlying their demise [*e*.*g*.,  @freitas-oliveira_no_2024; @lópez-aguirre2017; @tarquini2022; @prevosti2024].

Beyond competition, other biotic-driven hypotheses for the asymmetry of the GABI also refer to predation, emphasising a pre-existing predatory regime disequilibrium between the Americas. Once the continents were connected, this predatory regime disequilibrium would have benefited to the North American predatory migrants (*e*.*g*., felids, canids), to the detriment of the South American lineages that were not used to cope with intensive predatory pressure (*e*.*g*., sloths, native ungulates) [@faurby_asymmetry_2016].

The role of biotic interactions -- being either competition or predation -- in the asymmetry of the GABI remains untested from a mechanistic perspective. Future research could therefore involve to adapt a simulation framework such as the one implemented over \textcolor{Blue}{Chapter 3} by incorporating biotic constraints to species ecological niche. The flexibility offered by gen3sis, the mechanistic eco-evolutionary simulator that we used, offers a vast array of possible ways to do so [@hagen2021; -@hagen2023]. In addition, it would also be possible to test for a synergy between biotic and abiotic factors by implementing an environmental filtering function depending on the diversity of other species and one or several palaeoclimatic variables at the same time [*e*.*g*., @hagen2024]. That being said, establishing a new simulation landscape to model the GABI would greatly benefit from leveraging the numerous caveats that our pipeline comprised (@sec-GABI_lim).

Future improvements in mechanistic modelling of the GABI may notably require to extend beyond the last 5 million years, a time frame that we adopted for practical reasons -- *i*.*e*., the temporal coverage of the palaeoclimate reconstruction that we used [@barreto2023]. Although experts generally agree with an onset of significant land mammal exchange between the Americas being not earlier than *ca*. 3 Ma, the fossil record attests for the occurrence of earlier faunal exchange, notably among sloths (South-to-North, *ca*. 9 Ma), procyonids and cricetids (North-to-South, *ca*. 7 Ma) [*e*.*g*., @woodburne2010].

Should such a temporal extension be applied, the assumption of fixed palaeogeography on which the simulation landscape used across \textcolor{Blue}{Chapter 3} relied could no longer be maintained. Consequently, future works would crucially require the development of fine-scale time-continuous palaeogeographic reconstructions of the isthmus of Panama. The timing of such a closure has been much debated in the literature, with various sources of data sometimes resulting in contrasting interpretations [*e*.*g*., @bacon2015; @lessios2015; @marko2015; @montes2015; @odea2016; @jaramillo2018; @brikiatis2023]. To accommodate for a spatio-temporal uncertainty regarding the evolution of this geologically-complex area in upstream eco-evolutionary simulation studies, one avenue could involve to assemble various palaeogeographic scenarios, notably varying in the timing of the full closure of the isthmian region. Such a reconstruction might have broad implication, as it may also be used as a building-block for any study interested in reconstructing the historical biogeography of a clade related to Central/South America -- among the most species-rich regions of the globe[^discu-2].

[^discu-2]: The perspectives developed here, *i*.*e*., building a fine-scale time-continuous palaeogeographic reconstruction of the Istmus of Panama and subsequently using it in a simulation framework to test for the effect of biotic interactions in the establishment of the asymmetry of the GABI were formalised in a post-doctoral proposal currently under consideration.

All in all, the GABI remains a mysterious biogeographical event that, despite being the scope of intensive research efforts over the past 50 years, will probably remain unresolved for long. 30 years after publishing the cornerstone essay to which we refer earlier in that section [@simpson1950], Simpson wrote that the history of South American mammals "can be considered as an experiment without a laboratory, fortuitously provided by nature" [@simpson1980]. The term 'fortuitous' here adds an insightful perspective related to contingency, having a strong reasoning in the framework of the GABI : if things were to be repeated, perhaps the outcome would be different. Following that reasoning, we could even flirt with provocation and argue that the quest for the factors that underlay the GABI is vain. Maybe it entirely arose as a by-product of consecutive stochastic event that, taken as a whole, caused the demise of many endemic South American clades, to the advantage of North American ones.

Last, it is important to mention that, instead of being a consequence of the GABI, the relatively recent (Holocene) extinction of several emblematic endemic South American taxa (*e*.*g*., the native ungulate genera *Toxodon* or *Macrauchenia*; giant sloths; glyptodons) may also be regarded as a causality of Quaternary megafaunal extinctions [@croft2020]. The causes behind this well-described and intensively studied pattern remain under debate, but anthropogenic factors have been increasingly considered in that respect [*e*.*g*., @prates2021; @hauffe2024; @svenning2024; @boscaini2025].

### Future directions towards an improved understanding of the emergence and dynamics of South American ecosystems

Neogene

DIACHRONANDES, PHENOMENA

## Dealing with the Devil: uncertainties in the large-scale study of biodiversity

Lack of well-constrained phylogenetic framework, as many of the endemic Cenozoic South American mammal fauna has gone extinct

Traits mediate biotic interactions

Defining a species?

Reconciling the fossil record and molecular phylogenies?

### Detecting the legacy of deep-time environmental dynamics in the diversification of clades

The idea that clade macroevolutionary dynamics are influenced by environmental changes -- encompassing both biotic and abiotic factors [*e*.*g*., @barnosky2001] -- has been central to this doctoral work. As detailed in the \textcolor{Blue}{General Introduction}, testing the hypotheses relating clade diversification dynamics to environmental changes yielded substantial methodological improvements in the field of macroevolution [*e*.*g*., @condamine2013; @lehtonen2017; @palazzesi2022]. That being said, the philosophy behind nay model-based approach has always been to chose the 'least worst' model following a given criterion (*e*.*g*., likelihood-based approaches)

It is easy to draw biologically-irrelevant correlations, hence the importance of having clearly defined hypotheses prior any analysis.

Avenue: mechanistic modelling. Can be Mechanistic Eco-Evolutionary Simulations, but also causal inference, such as structural equation models or phylogenetic path analyses.

The uncertainty may never be solved. However, one approach to resolve it lies in combining several approaches [*e*.*g*., @toussaint2025]. That's what we intended to do with MBD/BDNN in \textcolor{Blue}{Chapter 2}.

Phylogenies are the big absent

### Apples, oranges and brushes: some of those biases that work forces at altering macroevolutionary pipelines

Data cleaning !

Lack of time-continuous proxy for precipitations.

### A matter of scales

Species of genera?

### Simulating biodiversity : expanding or narrowing the field of possibilities?

Strength of the simulation pipeline: leverage the caveats of the fossil record. Virtual experiments playing on single parameters [@hagen2023].

{{< pagebreak >}}
