# Glossary {.unnumbered header-title="Glossary"}

*This section intends to provide simple definitions to key notions and concepts to which this thesis refers. Note that some are complex and could be the subject of entire research works. Thus, these definitions do not aim to be as exhaustive as possible, but rather, to improve the reader's understanding of this manuscript.*

\noindent \textcolor{Blue}{\textbf{Adaptive radiation.}} Rapid *diversification* of a group taking advantage of a previously unexploited ecological dimension of the environment, generally spurred by a *key innovation*. Adaptive radiations are accompanied with ecological divergence. This concept has been proposed by @simpson1944.

::: {.content-visible unless-format="pdf"}
\noindent \textcolor{Blue}{\textbf{Angiosperm Terrestrial Revolution (ATR).}} Suite of major global-scale ecosystem reshaping that followed the radiation of flowering plants (angiosperms) in the Early Cretaceous (*ca.* 140 Ma). The term was introduced by @benton2022.
:::

\noindent \textcolor{Blue}{\textbf{Biogeography.}} Discipline aiming to describe and understand the spatial distribution of species.

\noindent \textcolor{Blue}{\textbf{Clade.}} Given a multi-species sample, a clade is an exhaustive subsample of all species sharing a common ancestry. Clades are referred to as *monophyletic*.

\noindent \textcolor{Blue}{\textbf{Diversification.}} The diversification process summarises the net evolutionary changes in a *clade* across time, that is, the gains (modelled by the *speciation* process) minus the losses (modelled by the *extinction* process). As such, it represents the process generating clade's diversity. The intensity of the diversification process (called diversification rate, often noted $d(t)$ for a given time $t$) is thus the difference between the rates of speciation and extinction, leading to $d(t)=\lambda(t)-\mu(t)$.

\noindent \textcolor{Blue}{\textbf{Ecological niche.}} The concept of ecological niche may be understood in different ways. In macroecology, the niche is more often viewed from a perspective of the species' requirements, therefore following the framework proposed by @grinnell1917 and later @hutchinson1957. Considering a landscape made up with $n$ ecological variables (*e*.*g*., climate, topography, abundance of other species, abundance of trophic resources, ...), the ecological niche of a given species theoretically represents the portion of the landscape where the species occurs. As such, it can be viewed an $n$-hyperpolygon encompassing the species' tolerance range following each variable (*e*.*g*., 15--25°C, 0--1000m, ...). Other definitions exist, such as the Eltonian niche @elton1927, more centered on species' impact on the environment.

\noindent \textcolor{Blue}{\textbf{Extinction.}} Process of disappearance of all representatives of a given lineage. In macroevolutionary modelling, extinction rates (expressed in event per unit of time) are often noted $\mu(t)$.

\noindent \textcolor{Blue}{\textbf{Latitudinal Biodiversity Gradient (LBG).}} Pattern of increasing species diversity with decreasing latitude (*i*.*e*., within a given unit of the globe's surface, the number of species within it increases as we get closer to the equator), found in a wide range of group.

\noindent \textcolor{Blue}{\textbf{Mass Extiction.}} Geologically-instantaneous event (order of magnitude $\approx 10^5y$ @guinot2023; @li2026) characterised by the loss of a significant proportion of the biosphere. Five major mass extinctions have been acknowledged to have impacted the Panerozoic history of life, termed the "Big Five mass extinctions" [@raup1982], but the definition of mass extinctions has been proposed to be extended to other intervals [@bambach2006; @hoyalcuthill2020].

\noindent \textcolor{Blue}{\textbf{Stochastic process.}} As opposed to *deterministic processes*, always resulting in the same output (*e*.*g*., Ordinary Differential Equations in Physics), *stochastic processes* are built upon one or several *random variables*, thus inserting some degree of randomness in their outputs governed by known probability laws. Stochastic processes are thus often appropriate to model biological systems, having some part of unpredictable behaviour (often termed 'noise') that cannot be rendered by deterministic processes.

\noindent \textcolor{Blue}{\textbf{Speciation.}} Origination of a new species from an ancestral lineage. There are several known types of speciation. Speciation is called allopatric when a physical barrier (*e*.*g*., a mountain, a river) subdivides an ancestral population into several sub-populations, thus interrupting gene flow and driving to the split in as many species as initial subsets by divergence accumulation. Conversely, a the barrier to gene flow arises within a population where individuals remain in connexion (*e*.*g*., behavioural barrier), people refer to *sympatric* speciation. When speciation arises from a founder effect, *i*.*e*., colonisation of a new area (*e*.*g*., an island), one refers to *peripatry*. A particular case of peripatry, when the colonised area is adjacent to the range of the initial species, is called *parapatry*. Given these several modes, modelling speciation can be done in different ways, defined in this glossary (*cladogenesis*, *anagenesis*, *budding*,). In macroevolutionary modelling, speciation rates through time, expressed in number of events per unit of time, are often noted $\lambda(t)$

\textcolor{Blue}{\textbf{Trait.}}
