# Introduction {.unnumbered}

South America =\> pt commun btwn ttes les parties !

South America as a bridge between macroecology/macroevolution? Partir SA et faire émerger des concepts style macroéco/macroévo

Neotropical diversification? Bring palaeoenv, sorte de follow-up à Hoorn et al. 2010?

Point epistémo paleo Fr: @servais2012

## What can we learn from biodiversity at large scales?

Define biodiversity.

Define macroecology =\> **refer to @diniz-filho2023**

Mammal macroecology: read @lyons2019

Species as an arbitrary unit to quantify biodiversity, changes occurring in a continuous manner. Remind the several definitions of species (*schéma gradient et seuil arbitrarire correspondant à ladite définition*)

Biodiversity is **uneven**:

- across space (insert map)
- across clades. Sister clades can be vary substantially in diversity : read @henao-diaz2023 + give examples. Empirical phylogenies are more imbalanced than predicted by simple models. Proposed drivers of this imbalance include (see @carrillo2026) + abiotic ? Radiation @simões2016
- across time

### The uneven spatial organisation of biodiversity

What would happen if we mapped the combined distributional ranges of all the species on Earth? Based on his long-term observations in the tropical regions around the world, first in Amazonia (1848--1852) and then in New Guinea (*Dates?*), Alfred Russel Wallace noticed that "*Animal life is, on the whole, far more abundant and more varied within the tropics than in any other part of the globe, and a great number of peculiar groups are found there which never extend into temperate regions*" (@wallace1878 *p.119*). Interestingly enough, his travel mate Henry Walter Bates was primarily struck by the relative scarcity, or even "*absence of animal life*" (@wallace1878 *p.70*) that appears to anyone first roaming by tropical forests, blurred by the fact that local fauna is in fact "*widely scattered and excessively shy of man*" (@wallace1878 *p.71*). Surprisingly,

**2 centuries after Humboldt, what do we know about the processes behind the spatial variation of biodiversity?** =\> review, replacing the different hypotheses in their context and placing an emphasis on the contribution of recently-developed frameworks (macroevolutionary approaches taking advantage of both fossils and phylogenies, eco-evolutionary simulations, deep-learning)

Rocha & Kaefer [@rocha2019] for a review of the hypotheses describing spatial variation of biodiversity, with an emphasis on tropical refugia.

Adaptive radiation : impulsed by @simpson1944, also see @schluter2000 and read @gavrilets2009

### Keys from the past: biodiversity as a dynamical entity

Mass extinction review?

Mass extinction among plants : @mcelwain2007

Historical biogeography: **review of @landis2026**

### The Latitudinal Biodiversity Gradient: a central and long-recognised pattern

Short review of the LBG. The different hypotheses that have been proposed, its conspicuousness across time and a wide range of taxonomic groups

## Towards a process-based understanding of biodiversity: history of the field from correlation to causation

Review the successive approaches developed to study large-scale patterns of biodiversity, and their limitations

- First approaches: linear modelling [@brown1989]
- The Golden age of Species Distribution (or Habitat Suitability / Ecological Niche) Models
- The rise and growing expansion of Mechanistic Eco-Evolutionary Models (MEEMs) [@hagen2023]

## Studying large-scale biodiversity patterns: an inherently biased science

Recap figure:

- 

  (A) Scheme of the 7 biodiv shortfalls

- 

  (B) Map across time to illustrate fossilisation and sampling biases

### A present-day perspective

The seven biodiversity shortfalls [@hortal2015].

### Reconstructing the past dynamics of biodiversity: a century-old milestone

Reviewing the methods to infer palaeobiodiversity. See @alroy2020

Studying past ecosystems primarily relies on the only source of direct evidence of biodiversity at a given time in the past: fossil data. All the aforementioned filters apply to the study of past ecosystems, or, more generally, to the temporal dynamics of biodiversity, but also, fossil data come with their own biases. Two main biases apply to fossil-based reconstructions of biodiversity: preservation and sampling.

All sources of data are also prone to another source of bias, coming from errors when entering them to lake them community-availableToday, open databases (e.g., PBDB) have become an essential building-block to modern macroevolutionary research relying on the fossil record. These databases centralise a wealth of fossil occurrences for a wide variety of taxonomic groups − at time of writing, PBDB contains \>1.98 million occurrences for \>516k taxa. Although, by essence, everybody can contribute to entering data, such databases are maintained by a relatively low number of people, of whom the expertise cannot span the entire spectrum of taxa represented. As a result, these large-scale databases are prone to a large number of errors (like those listed in the point 1), in turn affecting subsequent macroevolutionary analyses, stressing the importance to collaborate with taxonomic experts (A. F. P. Marion unpublished PhD thesis).

Given these biases, major paradigms in evolutionary biology have been questionned, such as the diversity decrease of non-avian dinosaurs prior to the Cretaceous-Palaeogene mass extinction [@barrett2009; @chiarenza2019 but see @condamine2021].

### Strategies to overcome these limitations

**Embrace uncertainty**

discussion from @hortal2015

model-based methods + simulations

This gap stimulated methodological improvements to account for sampling bias in biodiversity reconstructions [*e*.*g*., @silvestro_bayesian_2014; @kocsis2019; CITE MORE STUFF HERE].

Overcoming these limits have stimulated methodological improvements. The last decade marked the golden age of spatial standardisation procedures, borrowed from present-day ecology @chao2012, leading to deconstructing a wealth of paradigms in palaeontology [@mannion2013; @mannion2019; @close2020]. Instead of post-hoc corrections of diversity curves, the past decade also saw the onset of probabilistic framework explicitely incorporating a sampling process in the modelling of the time dynamics of the assemblages [e.g., @silvestro_bayesian_2014]. Now, deep-learning approaches @cooper2024

Also see @reijenga2025

## Macroevolution: evolutionary dynamics above the species level

### Epistemological framework

Modern synthesis of evolution: epistemological recap in @futuyma2015

It has long been established that biodiversity exhibits marked variations through time, that could not be explained by random fluctuations alone [@sepkoski1981]. A central aim in the study of deep-time biodiversity patterns has therefore been to elucidate the potential drivers behind the changes in the processes generating biodiversity [@vanvalen1973; @vrba1995; @barnosky2001; @benton2009].

Through geological times, species and higher taxonomic entities appear and go extinct, experiencing changes in their external environment during their respective lifespans. Seminal theories have been proposed to relate such environmental dynamics to the pace at which evolution occurs. Assuming species evolve in an environment made up with biotic -- other species -- and abiotic -- *e*.*g*., climate, topography -- compounds, @vanvalen1973 postulated that biotic interactions were the main drivers of evolutionary changes, leading to the Red Queen hypothesis. Conversely, other authors placed abiotic changes in the centre of the picture [@vrba1992; @vrba1995] -- sometimes even considering biotic correlates of evolution as a consequence of changes in species physical environment @vrba1993 -- further referred as the Court Jester hypothesis @barnosky2001.

### The concept of species, history of the irreconciliable

Studying evolutionary changes above the species level assumes that one is actually able to define what a species is.

On the difficulty to define species [@dequeiroz2007] and studying speciation in the fossil record [@benton2001]

Read @prothero2025 s On the need to use the fossil record to reconstruct evolutionary histories (primarily restricted to molecular phylogenies) : @quental2010

Mass extinctions: read @bambach2006

## What influences the dynamics of clade diversification?

Evolution and climate @vrba1995. Conflicting hypotheses regarding the drivers of large-scale evolutionary changes. Historical biotic vs. abiotic conflict @vrba1995. Updated integrative frameworks agree that both might be acting but on different scales [@vrba1995; @barnosky2001; @benton2009]. **Also see @jablonski2003**

### The Environment

**Red Queen & Court Jester**

See @liow2025

### Traits

Striking diversity disparities between sister clades showing differences in a key trait has long made researchers postulate that traits must act on diversification dynamics [refs within @ng2014]

Slight overview of trait-dependent diversification [rely on @morlon2024], SSE models, occurrence-based approaches, good points and caveats

Key innovations and adaptive radiations:

- early acquisition of hovering flight and nectarivory among birds likely promoted the radiation of hummingbirds (Trochilidae) [@mayr2004]
- early acquisition of echolochation likely favoured the radiation of bats [@hand2023]
- flower, along with other traits related to physiology (faster pace of living) promoted angiosperm radiation, Darwin's 'second abominable mystery' [@sauquet2017; @benton2022]

Nice case study where environment and traits drive spatial mismatch between diversity and diversification rate in a chinese plant genus (*Clematis*) : @zhang2026

## Studying diversification: a century-long tail in constant improvement

@yule1924 first derived a stochastic model to explain how species are distributed across genera, as well as to test some hypotheses, such as the relationship between clade age, diversity and geographic range.

@raup1973 : first development relying on palaeontological data

On the use of birth-death models in macroevolution: @nee2006 (early review)

### Phylogeny-based approaches

Brief catchy summary box of studying diversification using phylogenies with emphasis on EDD available in @hoorn2023

Limitations:

- Rely on a phylogeny, hence an assumption of the underlying relationships between the species of a clade
- Identifiability: not adapted for extant timetrees identifying the extinction and speciation rates is not possible [@louca2020]. Particularly, with phylogenies only including extant species, the recent speciation of modern lineages often masks the extinction signal in other parts of the phylogeny [@morlon2011]

### Fossil-based approaches

Phylogenetic approaches to study diversification are suited when the underlying relationships between species within a clade are well constrained. Although one can imagine this to be the case for phylogenies encompassing a large proportion of extant representatives, hence molecular characters

### Combined approaches

## South American mammals across the Cenozoic as a study model

### South America as a playground for eco-evolutionary biologists

Palaeonenv context throughout the Cenozoic

South America encompasses the highest extant diversity for a lot of groups, including mammals [@raven2020]

### A unique biogeographic history

Recap events enumerated by @croft2020, from Palaeocene to present. Read @croft_2012

One subpart per "big phase" + replace the emphasis of this PhD (Eocene–Oligocene; Late Neogene & Quaternary with GABI, Chinchi & Platy). **Adapt figure**

### South American mammals: toolkit

The very high and unique South American biodiversity has made the continent a true playground for famous naturalists, across the centuries just like Wallace. The latter, after spending four fruitful years in Brazil to investigate the Amazoniann biodiversity, unfortunately lost most of his scientific collections and productions on the way back to Europe, due to the burning of his ship in 1852.

Evolution in a vacuum impacted by various dispersal phases (FABI resulted in panperissodactyla, welker et al. 2015, Buckley 2015)

Taxonomic contrast with the fossil record =\> bring several questions related to the evolutionary fate of SAM.\
- 3 clades endemics to South America : Xenarthrans, SANU & South American metatherians (Simpson's Phase 1)\
- Palaeogene "newcomers": hystricognathous rodents and anthropoid primates. How tf?\
- Xenarthra issue : lack of fossil record prior to the early Eocene (Itaboraian SALMA, @fernicola2021), whereas we know that this radiation is exclusively restricted to South America (form the Atlantlogenata clade with Afrotheria, divergence age in the Cretaceous, *c*. 80 Ma )

### History of South American mammal palaeontology

Mammal remains from South America started to be studied as early as the early 1800s. Cuvier indeed described the famous giant sloth *Megatherium americanum*. A few decades later, Darwin, back from his five-years journey on board the HMS Beagle to explore and characterise the fauna and flora of the other side of the Atlantic, brought back to England a wealth of material, including fossil specimens, and gave them to Richard Owen so they can be studied. In the years following Darwin's return to England, Owen therefore described several of the most famous fossil mammals from South America, including *Glyptodon*, *Macrauchenia* or *Toxodon*.

In his journey on the continent, Darwin also unearthed remains (locality name?)

Simpson

Scientists from the continent (mostly from Argentina): Florentino & Carlos Ameghino, Carlos de Paula Couto (Brazil), Lucas Kraglievitch

a wealth of bizarre forms

*Figure with portraits of all the names mentioned?*

::: {.content-visible unless-format="pdf"}
## Side notes

Read [@dasilva2025]

Read [@gaston2000]

Read [@davis2005]

"\[...\] evolution occurs at different temporal and geographic scales, and at different organisational levels of the biological hierarchy--including the levels of genes, cells, organisms, populations, and species." [@vrba1995]

### On the importance of stochasticity in life-related processes

Evolution is not deterministic. Traditionally, people tend to invert the cause and the consequence.

Life across interconnected scales, from molecules to biosphere. Changes occur stochastically and are then subject to external filters. Continuous accumulation of changes

Hubbell's neutral theory of Biodiversity: quantitative null model emphasizing how natural randomness shapes evolutionary processes [@hubbell2001; @rosindell2011]
:::

## Aim of the thesis and study plan
