# Remerciements / Acknowledgements / Agradecimientos {.unnumbered header-title="Remerciements / Acknowledgements / Agradecimientos"}

::: {.content-visible unless-format="pdf"}
Back in the days, Aristotle famously wrote that "*The more you know, the more you realise you don't know*". This statement has a particularly strong reasoning at the time I jump into the first lines of what is supposed to be the achievement of three years of intense labour on a topic on which I will apparently become an *expert* of.

Tempérons les ardeurs des méritocrates invétérés qui verront en cet essai signé de la main d'un fils d'ouvrier du bâtiment/intermittent du spectacle et d'animatrice en EHPAD la matérialisation du fantasme bourgeois du "*Quand tu veux, tu peux*". Non, je n'ai pas grandi dans l'opulence, mais j'ai toujours joui d'un soutien inébranlable, que ce soit sur le plan matériel, intellectuel ou émotionnel, soutien pour lequel je ne pourrais jamais suffisamment remercier mes proches, en première ligne desquels se trouvent mes parents. J'ai grandi à mille lieux de là où se concentre la violence du système, dans un petit coin de campagne tranquille et hors d'une quelconque minorité. Donc finalament bien armé pour affronter le système.
:::

## Jury

I first warmly thank my PhD jury, \textcolor{Bittersweet}{Darin A. Croft}, \textcolor{Bittersweet}{Tiago B. Quental}, \textcolor{Bittersweet}{Erin E. Saupe} and \textcolor{Bittersweet}{Frédéric Delsuc}, for accepting to endorse the role of evaluating my doctoral work. Hopefully this manuscript won't spoil too much of your summer! I also thank the members of my PhD committee, \textcolor{Bittersweet}{Gilles Escarguel}, \textcolor{Bittersweet}{Ignacio Quintero}, \textcolor{Bittersweet}{Ana Rodrigues} and \textcolor{Bittersweet}{Myriam Boivin} for their involvement. The two meetings that we had were highly insightful to me. Mention spéciale à Ana, merci de m'avoir convié à partager ce repas avec ton équipe au CEFE, et de m'avoir reçu par la suite pour dialoguer informellement du monde académique. J'ai énormément apprécié ce petit bol d'air extérieur. Mention aussi toute particulière à Myriam avec qui, au gré de la thèse, j'ai eu la chance d'amorcer une collaboration donnant lieu à ce joli chapitre sur les chinchilloïdes. Merci beaucoup d'avoir accepté de travailler avec moi sur ce groupe absolument passionnant, en y investissant toute ta rigueur et ton sérieux malgré tes contraintes familiales. J'espère avoir l'opportunité de continuer à collaborer avec toi dans le futur.

## Encadrement

\textcolor{Bittersweet}{Merci Laurent} pour ton optimisme inébranlable, qu'il s'agisse de tes "yeux bleus loupés", de ton mode de vie de "curé", de ta quinzième mission de terrain à l'autre bout du monde où tu feins de te rendre à reculons en clamant que, cette fois-ci, c'est la dernière et que tu es "trop vieux pour ces conneries", ou du fait que tu es tout simplement "bon à jeter", faisant preuve d'une inspiration débordante dès qu'il est question d'auto-flagellation (kong!). Plus sérieusement, merci pour ces trois années que tu m'as offertes. Bien qu'étant fort incapable de déchiffrer, à ta manière, l'histoire de la vie inscrite dans ces enchevêtrements de cingulums, talonides et autres hypoconules fossilisés (ton "business" comme tu dis), j'ai énormément appris de ta connaissance intégrée sur tes modèles d'étude de prédilection dont, je l'espère, mon travail rendra un hommage un tant soit peu comparable à l'attrait que j'ai développé pour l'histoire évolutive de ces groupes en te cotoyant. Je te remercie également pour l'intérêt sincère que tu portes à ma recherche, je me sais très chanceux d'avoir pu jouir d'un encadrement sans faille de ta part, à l'image de la rapidité fulgurante avec laquelle tu relis mes manuscrits. Merci aussi pour ces expériences uniques que j'ai passées en ta compagnie sur le terrain. Si l'on enlève quelques ronflements survenus alors que nous partagions cette magnifique chambre à *La Pradera* où je me faisais un malin plaisir de couper l'air conditionné dès que tu avais le dos tourné, je garderai un excellent souvenir de nos conversations échangées sous la chaleur écrasante de l'Amazonie en pleine journée, à donner des coups de marteau dans du sédiment, à "branler du tamis", ou le soir autour de la bino, en sirotant une *Cusqueña* ou un *Pisco Sour*. Tu as un vécu remarquable, et je te souhaite sincèrement de faire de toutes tes anecdotes de terrain un livre: il faut que le monde sache ! Enfin, en plus d'être un brillant scientifique, tu es d'une gentillesse sans pareil. Il n'y avait pas que de l'ironie quand je te comparais à mon grand-père sur le terrain: ta bienveillance dans les interactions que nous avons pu avoir m'a, par moment, ramené à un cadre presque familial. Tes passage éclair dans mon bureau, laissant seulement entrevoir ta tête habillée d'un sourire espiègle sans mot dire, me manqueront. Aussi, merci pour tout, et j'espère que j'aurai de nouveau affaire à ton crâne si régulier -- qui laisse rêveuse ma dolichocéphalie, comme tu l'as très justement souligné -- et tes contrepèteries dans le futur !

\textcolor{Bittersweet}{Merci Fabien}. Quelques semaines à peine après ma venue à l'ISEM, tu m'as dit une phrase qui, je pense, s'avère être le meilleur conseil que l'on m'ait jamais donné en sciences, à savoir: "Un bon chercheur, c'est avant tout un bon lecteur et un bon écrivain". Merci beaucoup d'avoir partagé un peu de ton enthousiasme inflexible, de ta soif inétanchable de savoir, de tes capacités réflexives hors du commun et de ton regard intégré sur un large pan de la biologie évolutive avec moi. Par bien des aspects, tes qualités professionnelles font de toi quelqu'un de très inspirant, même si je pense qu'elles te jouent aussi parfois des tours, comme en témoigne ce florilège de cheveux blanchissants illuminant ton implantation capillaire absolument remarquable pour un quadragénaire -- dont je suis d'ailleurs jaloux, et sûrement que Laurent aussi ! J'ai énormément savouré nos interactions enrichies de ta connaissance encyclopédique (devrais-je même dire autistique ?) de la littérature. Tu es plein de ressources, et je pense que travailler à tes côtés n'a fait que renforcer ma motivation à faire de la science, surtout quand nos sessions de travail nocturnes impliquaient également la consommation d'un saint breuvage anisé pour lequel nous partageons une appétence toute particulière (merci papa). J'espère sincèrement pouvoir être amené à travailler de nouveau avec toi dans le futur. Enfin, merci énormément de m'avoir communiqué la moindre offre de post-doc de ton réseau tentaculaire qui te paraissait coïncider avec mon profil, et de m'avoir proposé d'assister à ce Workshop à Arles avec toi et Romain qui, si l'on met de côté un pneu de vélo crevé et une voiture à la fourrière, restera sans doute le meilleur événement scientifique auquel j'ai assisté au cours de ma thèse. Je te suis sincèrement reconnaissant pour toutes ces attentions.

\textcolor{Bittersweet}{Muchísimas gracias por todo Sara (Varela)}, sea por los proyectos súper bonitos que llevamos haciendo desde un par de años ya, o por tu apoyo constante, que no tiene valor en el sistema académico, individualista y súper competitivo. Por varios motivos eres una persona muy inspirante, por lo listo, entusiasta, determinado y profundamente majo y empático que eres. Creo que por culpa tuya, parte de mi corazón científico-personal se quedó en Galicia para siempre. Gracias a tí y a tu equipo, pase unas semanas inolvidables en Vigo durante de mi experiencia doctoral. Te agradezco también por haberme invitado a este congreso en Pontevedra el año pasado, que estuvo una experiencia muy bonita. Espero que seguiremos trabajando juntos, y te deseo lo mejor para el futuro.

## Fundings / Financements

Merci au CROUS et aux bourses pour m'avoir accordé une autonomie financière au cours de mes deux premières années d'études supérieures. Merci au salaire normalien pour les quatre suivantes. Merci au contrat doctoral spécifique normalien pour les trois dernières. Je suis conscient de l'extrême privilège auquel j'ai pu jouir en bénéficiant d'une rémunération continue au cours de mes études. Je suis également conscient de la chance que j'ai eue d'accéder aux classe préparatoires aux grandes écoles (CPGE) en pouvant bénéficier d'une pension complète à moindre frais à l'heure où les lois du marché font rage et, au bas mot, sous-tirent chaque mois aux étudiant-es en loyer le montant trimestriel auquel me revenait ma pension en CPGE (logement + nourriture à 3 repas par jour). La violence des inégalités du système me laisse particulièrement amer, posture bien facile à tenir du point de vue de celui qui a pu en bénéficier. J'en profite alors pour affirmer mon soutien le plus inconditionnel à la gratuité totale de l'ensignement supérieur, pour tous-tes, peu importe l'origine sociale ou géographique (car oui, il est actuellement question d'imposer des frais d'inscription aux études Universtitaires mirobolants pour les étudiant-es étranger-es) et à toute initiative de lutte contre la précarité étudiante.

Thanks to the Labex CEBA (via the EMERGENCE project) for financing my attendance to the GTÖ Lisbon (02/2024) congress as well as for funding the two missions I had the immense privilege to do in Colombia Peruvian Amazonia, and for covering the APC of my first PhD paper. Thanks to the ECOS-Nord for funding travel tickets to Colombia last year. Thanks to my two teams (PEM and PAL) for their support to attend PalAss 2024 and 2025. Thanks to The Palaeontological Association for allocating me travel grants two years in a row. Thanks to Thomas J. Smith, Erin E. Saupe (again!) and her NERC project for organising this highly insightful workshop about spatial methods to study the fossil record in Oxford (03/2024). Thanks to Alexis Licht and ERC DISPERSAL for organising BIOGEOPHYLO workshop (03/2025), probably the most inspiring and interesting scientific event I have had the chance to attend so far. Thanks to the ERC-funded project MAPAS for financing my tickets to Vigo in June 2024. Thanks to the École Doctorale GAIA for travel grant to attend AEET-SIBECOL joint congress in Pontevedra and my subsequent stay in Vigo (06/2025).

## ISEM-related

### Les Actuel-les

Ensuite, \textcolor{Bittersweet}{merci PierrO}. On ne va pas se mentir, en faisant une thèse sur les mammifères sud-américains, même si tu n'étais pas dans mon encadrement officiel, à bien des reprises, ton expertise intégrée sur les faunes et les paléoenvironnements de ce continent fascinant ont été utiles à mon travail, si bien que tu m'as très certainement parfois encadré de manière non-officielle (t'inquiète, je dirai rien à l'ED). Merci pour ça. Merci aussi énormément de m'avoir offert ces deux opportunités uniques de vous accompagner, toi, Lolo, Narla et François (une année sur deux pour le père Pujos) sur les traces des faunes éteintes d'Amérique du Sud tropicale. En mettant de côté quelques petites filouteries, comme la fois où nous nous sommes rendus au quartier des garages de Bucaramanga, ne faisant pas fière mine d'être les deux seuls blancs, pour racheter le miroir d'un rétroviseur que l'on nous avait volé quelques jours plus tôt, ou quelques mésaventures intestinales dont je passerai les détails, ces moments sur le terrain à l'autre bout du monde resteront à jamais gravés dans ma mémoire, et tu en as été l'un des acteurs principaux. Je ne te remercierai jamais assez pour ça. Merci aussi pour ta confiance en m'ayant impliqué dans ton projet ANR PHENOMENA. Je mesure la chance que j'ai de jouir d'une telle opportunité à un stade aussi précoce de ma carrière, et je t'en suis très reconnaissant. Merci aussi pour ces moments sportifs que nous avons partagé, à l'occasion du Marathon par équipes de Montpellier, des footings de relâchements à Lima et Bucaramanga après d'interminables journées de transit (pas intestinal cette fois !!) ou, plus récemment, sous la fraîcheur palavasienne à l'occasion des 24h St Pierre que nous avons remporté il y a quelques semaines. Il faut quand même reconnaître que, malgré ton âge vénérable, tu en as encore un peu sous la pédale ! En parlant de pédale (oulah, transition douteuse), merci aussi pour ces moments musicaux où j'ai eu l'honneur de partager la scène avec tes coups de caisse claire, charlet et tomme basse dynamiques sur une batterie montée à l'envers qui partait en furie dès qu'elle entendait le nom "Zebda", faisant ressortir ses ardeurs Toulousaines. Je concluerai donc cette tirade infinie en disant que, n'en déplaise à toute considération d'horizontalité hiérarchique, il faut reconnaître qu'à bien des égards t'es le boss !

J'en profite aussi pour te remercier \textcolor{Bittersweet}{François}. Je suis heureux d'avoir partagé cette mission de terrain avec toi en Amazonie en 2024, on ne s'ennuie pas en ta compagnie... Kong ! Merci aussi de m'avoir fourni certaines des illustrations qui habillent ma thèse.

También quería agradecer a nuestros colegas paleontólogos peruanos, en particular los que se me ha dado la oportunidad de conocer, es decir Rodolfo Salas Gismondo, Raffo Varas Malca y Mario Urbina. Gracias por mantener esas colaboraciones, sin las que proyectos como el mío nunca podrían existir. Raffo, ha sido un placer compartir este congreso contigo en Inglaterra este año. Mucho ánimo con la tésis, y voy con ganas de verte presentar de nuevo sobre tus focas. También, gracias a tí Percy, el macho más guapo de la Selva, "soltero pero nunca solo".

Merci au \textcolor{Bittersweet}{reste des équipes PEM et PAL} pour l'environnement de travail unique dont j'ai pu bénéficier au cours de ces trois années. J'avais parfois la sensation étrange d'être un peu en grand écart permanent, pas suffisamment moléculaire pour être un PEM, mais pas assez qualifié en systématique pour un PAL. Merci tout de même de m'avoir accepté et intégré ! **Côté PAL**, \textcolor{Bittersweet}{merci Guillaume} pour ces quelques échanges au détour d'un café ou autre, et, plus généralement, ton regard très intégré sur les questions de macroévolution et le registre fossile et ton appétence -- partagée -- pour les douceurs anisées. \textcolor{Bittersweet}{Merci Romain} pour à peu près la même chose, je te souhaite le meilleur pour tes projets à venir. \textcolor{Bittersweet}{Merci aussi à Fabrice et Renaud} pour ces très chouettes moments musicaux, et \textcolor{Bittersweet}{merci Maëva} de m'avoir fourni quelques-unes des illustrations qui ornent mes transitions entre chapitres. **Côté PEM**, \textcolor{Bittersweet}{merci Manu} pour ton soutien au détour de quelques mots dans le couloir ou en salle café, ta bonne volonté et ton entrain sincère et particulièrement inspirant dès qu'il est question de sciences. L'un des plus grands regrets de ma carrière d'étudiant est de ne pas avoir eu la chance d'assister à l'un de tes cours, dont on m'a conté monts et merveilles. \textcolor{Bittersweet}{Merci Mathou} pour ton sourire, ta bienveillance et tes encouragements quand la fin approchait. J'espère que tu continueras à t'éclater dans ton post-doc à venir. \textcolor{Bittersweet}{Merci Benoit (Nabholz)} pour ton entrain à te creuser la tête sur des questions d'évolution générale, de statistique ou de programmation. Merci aussi de m'avoir permis d'enseigner dans ton UE de L3, je garderai de délicieux souvenirs de ces séances de TP données en ta compagnie. \textcolor{Bittersweet}{Merci PH} pour ces quelques conversations absolument passionnantes sur la biogéographie insulaire, les muridés de Papouasie-Nouvelle-Guniée et les Hutias. \textcolor{Bittersweet}{Obrigado Marisa}. És uma pessoa brilhante e atenciosa. Desejo-lhe o melhor para o futuro. \textcolor{Bittersweet}{Merci Elo} pour ta dévotion dans l'organisation des événements des non-permanent-es et pour ces quelques conversations au bar qui m'ont bien amusé. \textcolor{Bittersweet}{Merci Nathanaëlle}, bon c'est vrai que t'es plus en PEM mais il fallait bien que je te mette quelque part ! Merci pour ces moments musicaux habillés de ta magnifique voix, et plein de bonheur avec ton petit bout ! \textcolor{Bittersweet}{Merci Marie (Riffis)} d'avoir rythmé notre magnifique formation *Viva la Evolución* avec ce bon PierrO et de nous avoir assuré une sonorisation optimale. \textcolor{Bittersweet}{Merci Alba}, la meilleure co-bureau que n'importe qui puisse souhaiter -- même si je ne donnerais rien au monde pour être à la place de ton clavier quand tu codes. Je te souhaite le meilleure pour la suite.

\textcolor{Bittersweet}{Merci à mes petits golmons} d'avoir égayé ma dernière année dans ce laboratoire. Vous êtes tous-tes des individualités incroyables, et comme souvent en biologie, le tout vaut plus que la somme des parties -- serait-ce la propriété émergente de la débilité du rez-de-chaussée ? \textcolor{Bittersweet}{Merci Binou}, l'architecte du kiff sous shatta/boom-boom, pour tous ces agréables moments et ces teq-pafs passés en ta compagnie. T'es hyper bon délire, et je crois qu'avec un scientifique de ta qualité, le décodage de l'histoire évolutive des cétacés est promu à un avenir radieux. Je te souhaite le meilleur pour la suite, et je ne désespère pas de te voir ré-enfiler tes pointes un jour et t'imposer comme le prototype ultime de l'athlète hybride. \textcolor{Bittersweet}{Merci Nico} (te mentionner en #2 s'imposait ici comme une évidence), "le fer de lance de la paléomammalogie Languedocienne" comme l'a un jour dit quelqu'un de très sage, dont l'étendue de la culture générale n'a d'égal que le découpage du monde dans la tête d'un communiste internationaliste: sans limites, sans frontières ! T'es un crack et c'est beau de voir un mec aussi passionné que toi, que du bonheur pour la suite. \textcolor{Bittersweet}{Merci Hugo}, *aka* le bienfaiteur de la chauve-souris fossile, la force tranquille, le roc de Mondial 98. C'est sincèrement agréable de côtoyer un mec aussi sympa que toi au quotidien, et si l'on omet ton attrait presque religieux pour les voitures qui vont vite, t'as vraiment des qualités personnelles (et scientifiques) remarquables ! Que du kiff et du bonheur pour la suite. \textcolor{Bittersweet}{Merci Benoît}, l'empereur Moison qui, du haut de son mètre 90 perché, segmente ses dents à la perfection. Je dois dire qu'entre toi et Hugo je ne sais pas qui est la plus grande crème, mais toujours est-il que tu es d'une sympathie rare, et j'apprécie énormément papoter avec quelqu'un d'aussi intéressant que toi -- merci aussi pour mon gateau d'anniversaire hihi. Il va également sans dire que je mesure la chance inestimable qu'il m'ait été donné de partager la scène avec un saxophoniste de ton acabit. Merci pour tout en tous cas beau gosse ! \textcolor{Bittersweet}{En parlant de musicien exceptionnel}, ne serait-ce pas le moment de remercier le Duc des hippopotamoïdes, l'homme à la voix caverneuse avec qui j'ai eu la chance de partager mon bureau toutes ces années durant ? \textcolor{Bittersweet}{Merci pour tout Lorenzo}, ce n'est pas demain la veille que je re-jouerai avec un bassiste de ta pointure, et je pense que ton dramatisme méditerranéen à chacune de tes entrées fracassantes dans le bureau, à base de "il fait 10000 degrés dans ce pays!", "il fait tarpaing froid!", "j'ai envie de crever!" me manquera. Plein de courage pour la fin de ta rédaction, change rien en tous cas, sauf tes cordes ! \textcolor{Bittersweet}{Merci Antoine}, le beau bronzé aux yeux bleus du premier étage que les femelles babouins namibiennes doivent s'arracher presque autant que tu n'arraches de victoires aux concours de fléchettes du Tarbrew. Je n'ai pas beaucoup répondu "présent" à tes maintes sollicitations de sorties des derniers mois, je m'en excuse et compte bien me rattraper plus tard. Plein de kiff pour la suite ! \textcolor{Bittersweet}{Merci Malo}, même si tu taffes sur des trucs chelou, t'es cool ! \textcolor{Bittersweet}{Merci Amel} (enfin on équilibre un peu le sex-ratio calamiteux des golmons du rez-de-chaussée), t'es rentrée dans nos vies comme dans un freestyle, et je suis heureux d'avoir partagé mes six derniers mois avec une co-bureau de ta qualité. Merci aussi d'apporter un peu de politisation dans ce monde de brutes, nos petites conversation me manqueront. En tous cas, ne change rien, t'es incroyable, et je te souhaite tout ce qu'il y a de meilleur pour la suite de tes aventures pangénomiques ! Enfin, *last but not least*, le meilleur pour la fin, le pape de la systématique et de la macroévolution des plantes, l'*Apocyna-king*, celui dont la gentillesse, la générosité et le savoir n'ont d'égal que la longueur de ses tunnels: \textcolor{Bittersweet}{merci au sultan Boughalmi} ! Quelle joie d'avoir pu te rencontrer ce semestre Khalil, t'es une vraie perle, et j'espère sincèrement que nos chemins scientifiques ne se sépareront pas de sitôt... Qui sait, peut-être qu'on se retrouvera co-PI plus tard, pourquoi pas même avec ce beau Nils ? En tous cas je te souhaite le kiff ultimes pour tes 5 années de PhD dans l'opulence Helvético-Malgache.

### Les Ancien-nes (et apparenté-es)

\textcolor{Bittersweet}{Merci Alexis}, mon bebou, mon Ducont, mon sang de la carotide. Merci pour ces quelques années où j'ai pris énormément de plaisir à partager le même bureau que toi. Malgré ton changement d'orientation (pas sexuelle hélas, à mon grand désarroi et aussi à celui de mon pote Anto), je persiste à penser que nos interactions scientifiques journalières ont été très bénéfiques. Ta curiosité et la profondeur de tes réflexions m'ont à maintes reprises poussé hors de mes retranchements, et je pense que tu m'as aidé à devenir meilleur, sensei (horrible phrase de weeb capitaliste, je me dégoûte). Je garderai un souvenir ému de la fois où tu m'as appris à rouler des california rolls comme un pro avant de finir sur tes épaules dans le bureau de Fabien, complètement fracassé, quelques heures plus tard, ou de nos péripéties britannico-germaniques. Aucun commentaire sur ces dernières, à part peut-être qu'il n'y en a vraiment pas un pour rattraper l'autre ! Je suis très content de te compter parmi mes amis, tu es une belle personne, et même si t'as un chat chelou je te souhaite tout le bonheur du monde pour la suite de tes projets !

\textcolor{Bittersweet}{Merci Arthur}, la divinité suprême de la queue préhensile. T'es pas loin de compter parmi mes plus belles rencontres montpelliéraines avec ta tête d'ange et ta pillosité facio-capillaire à en rendre jaloux plus d'un (Lolo, si tu lis jusque là, sache que t'étais visé) ! J'ai encore en tête la douce mélodie de ta voix caverneuse teintée de ton délicat accent Alsacien[^remerciement-1] en train susurrer: "*La seule chose prrrroductive[^remerciement-2] chez moi, c'est mes ch'veux*". Mais tu n'es bien-sûr pas qu'une boule (et un sacré boule !) de poils "trop MIGNONNE" comme dirait, en serrant les dents, une personne remerciée un peu plus bas quand un félin domestique a le malheur de croiser sa route. Tu es aussi quelqu'un avec qui j'ai énormément plaisir à traîner en terrasse, faire la fête, et papoter, même quand ça implique de me prendre des tunnels de 45 minutes sur random ratou de Papouasie Nouvelle-Guinée ou sur à quel point la Meteor est une bière incroyable (*beurk*). T'es brillant, t'as plein d'idées, je pense que t'as vraiment tes cartes à jouer dans la recherche. En tous cas, la recherche a besoin d'esprits comme toi. Tout le meilleur du monde pour la suite, et pars pas trop loin trop longtemps stp !

[^remerciement-1]: Ah non pardon, Franc-Comtois ! C'est vrai que c'est pas la même. Y'avait pas un dicton du style "Comtois rends-toi, méni ma foi" ? Punaise, j'aurais jamais autant entendu parler de ce pays reculé qu'à Montpellier, mais je vous pardonne vous avez du bon fromage !

[^remerciement-2]: Je viens de percuter, mais "Produc'tiff" ça ferait-y-pas un joli nom pour un salon de coiffure ? J'ai google le truc premier degré et j'ai rien trouvé en plus...

Puisque j'ai fait l'un, j'en profite pour faire l'autre: \textcolor{Bittersweet}{Merci Céleste} ! T'es vraiment une chouette personne, et au-delà du fait que c'est quand-même vachement moins cher de sortir au bar quand c'est ta/ton pote qui sert, j'ai passé des super moments avec toi à parler de tout et de rien. Merci pour tout et tout le bonheur du monde pour la suite !

\textcolor{Bittersweet}{Merci Alex}, mon beau chamois, roi des forêts et des monts des Alpes provençales ! Quel plaisir de te savoir là-bas en train de vivre ta best life en trail ou en VTT, à me dire que certaines de tes journées de travail ressemblent à ce à quoi j'aspire de plus beau pour mes vacances. Quel plaisir aussi de me dire que je compte un flic dans mes amis -- oui oui je sais, la Police de l'Environnement vous êtes un peu les cool kids des cowboys en képi, mais c'est quand même assez rigolo. Merci pour ces petits moments passés en ta compagnie, on n'a pas tant galopé ensemble pour le moment mais, comme disent les gens de ton âge, "tout vient à point à qui sait attendre". Je passerai te voir, promis, en attendant porte-toi bien, affûte-moi ces blagues de daron et renforce-moi ces mollets gros gourmand !

\textcolor{Bittersweet}{Obrigado Narla}. Merci pour ces deux superbes campagnes de fouilles dans l'Amazonie péruvienne, ces moments resteront gravés à jamais dans ma mémoire. Quel dommage que tu n'aies pas eu la chance de recontrer ce beau *Salomón*... J'avoue que le petit grain jugeant de ta voix teintée de ton subtil accent entremêlant sonorités Brésiliennes et Paloises, dont toi seule a le secret, me manque un peu par moments. Merci aussi pour ces superbes moments festifs montpelliérains, et notamment dans ce bar clandestin Brésilien où j'ai passé d'agréables soirées ! Enfin, merci pour tes petits messages de soutien pendant la rédaction. Tout le meilleur pour la suite de tes aventures, et puisse le sort te faire regagner ton Brésil natal, loin de ces drôles de personnes que sont les Argentins...

En parlant d'Argentins... \textcolor{Bittersweet}{Merci Céline} pour ces joyeux moments partagés, et notamment sous les couleurs du club de handball du personnel de la fac, avec qui j'ai pris énormément de plaisir à retoucher un peu du ballon. Plein de bonnes énergies pour la suite de tes aventures, la micro-usure chez les caviomorphes a encore tant à livrer... Trop content pour ton projet en Suisse en tous cas !

\textcolor{Bittersweet}{Merci Fred (Lozes-Méléro)}, mon premier stagiaire. Je garde un souvenir extrêmement positif de cette expérience de travail avec toi, teintée de ton subtil et fier accent Tarn-et-Garonnais, et je suis ultra heureux de te voir continuer sur une thèse en macroévolution dès Septembre, même si, à mon grand damn, tu quittes les vertébrés (en vrai, je dis ça mais ça a l'air stylé les bousiers...). Tout le courage du monde pour cette nouvelle page de ta vie qui s'écrira en Finlande, en tous cas je compte bien faire en sorte que ton projet de stage soit mené à bout et, qui sait, peut-être qu'on finira collègues à la fin (je vais vraiment finir par monter l'Université du kiff moi à force de vouloir collaborer avec tous mes potes) !

\textcolor{Bittersweet}{Gracias Isabelle}. Eres un sol, y te deseo lo mejor para el futuro. ¿Quizás volverás por aquí por la tésis?

\textcolor{Bittersweet}{Merci Sonny}, sans qui les afterworks auraient été bien plus tristes. C'est toujours un plaisir de te croiser derrière le bar, et peut-être qu'on finira par se le faire ce trail ou cet hyrox?

\textcolor{Bittersweet}{Merci Nathan} pour ces chouettes moments passés à parler politique, musique ou à assister à de jolis concerts (ou les trois à la fois). T'es un chouette gars, je te souhaite le meilleur du monde pour tes projets à venir.

\textcolor{Bittersweet}{Merci Ariane}. Sans exagérer, tu comptes parmi mes plus belles recontres montpelliéraines. Merci pour tous ces moments passés en ta compagnie, en terrasse, en intérieur, chez les uns ou les autres ou en rando. Je ne me lasserai jamais de la diversité d'onomatopées que tu es capable d'émettre pour manifester ton désir de caresser le moindre félin ayant le malheur de croiser, de près ou de loin, ton chemin. Tu es queqlu'un d'extrêmement intéressant, avec qui j'ai énormément de plaisir à passer du temps. Je te souhaite réellement un peu de bonheur dans ce tunnel compliqué dans lequel l'injsutice du système t'a plongée, tu le mérites. Plein de love, et j'espère te compter longtemps parmi mes amis.

\textcolor{Bittersweet}{Merci Nono}, la queen des parnasses et des Thecosomata. Tu es une personne remarquablement sincère et empathique, avec qui j'ai également énormément de plaisir à passer du temps. J'admire aussi pas mal ta motivation et l'énergie avec laquelle tu t'investis dans tes projets pro comme perso. Pas trop de doute que la recherche est faite pour toi, même si ta présence nous manque un petit peu à l'ISEM (et j'ai pas parlé de ton boule)... Mais ainsi va la vie ! Merci pour tous ces petits moments, merci d'avoir été là quand j'avais besoin de parler, tu comptes énormément. Que du bonheur et de la réussite dans tes projets futurs.

## Sport-related

Merci aux potos du MAT pour ces magnifiques moments sportifs ! Mention toute particulière à \textcolor{Bittersweet}{Loïc, Romain, Nico, Augustin} pour ces belles sorties vélo et ces chouettes séances de papotage, vous êtes des chouettes gars, que du bonheur à vous. Merci aussi à \textcolor{Bittersweet}{Théo} la figure de proue des gros beaux gosses d'EDF. \textcolor{Bittersweet}{Merci François}, le daron bigourexique qui nous enterrera tous, en sport et à l'apéro. \textcolor{Bittersweet}{Merci Julie}, sans qui les optométristes feraient un bien triste métier. \textcolor{Bittersweet}{Merci Pierre, Mathilde, Franck, Fran, Christian}, vous êtes cools, et Pierre ton mulet est incroyable. \textcolor{Bittersweet}{Merci Micka}, t'es un giga-crack, j'ai hâte de me remettre des boîtes sur la piste avec toi.

Merci à l'équipe de la piste du Jeudi midi, en particulier Louca, Stéphanie, Olivier, Ulysse, Ulysse (oui, y'en a deux, c'est fou), Gaël, Alex, Caroline et, bien évidemment, notre illustre championne \textcolor{Bittersweet}{Fiona}. C'est trop cool de s'entraîner avec des gens comme vous, et absolument incroyable de côtoyer des athlètes de l'acabit de Fiona qui gardent une telle humilité, c'est très inspirant.

\textcolor{Bittersweet}{Merci Laurent Pouyaud} pour cette belle expérience des 24h St Pierre, ponctuée par une victoire de la *Wolfpack du Pic*, venue égayer ma rédaction de la meilleure des façons. J'ai passé un excellent moment à (m/c)ourir pour toi, on remet ça quand tu veux !

## Amigos de Galicia

\textcolor{Bittersweet}{Gracias Sofía}. Eres una persona súper antenta y profundamente lista. Gracias a tí y a Dani por haberme alojado durante de las dos estancias gallegas que hice estos últimos años. Te deseo lo mejor por tu post-doc en Oxford, ¡te lo mereces! Ojalá un día firmamos un paper juntos. \textcolor{Bittersweet}{Gracias Sara (Gamboa)} por tu cariño maternal, que dentro de pocos meses tomará ya una otra dimensión -- me alegro por tí y por tú hijo que va a tener una mamá extraordinaria. Eres una crack, sea como científica tal como persona. Mucho ánimo por la continuación de tus proyectos. Gracias a los demás mapit@s, \textcolor{Bittersweet}{Graciela, Andrea, Iván y Adriana} por dar a este equipo su buena onda.

Por fín, muchísimas gracias a los cerdos de la calistenia, y en particular, ¡gracias a tí Osí!

## Ami-es Lyonnais-es

Merci aux copaines que je côtoie depuis mon arrivée dans la capitale des quenelles et du saucisson brioché, en 2019 (même avant pour certains).

En particulier, merci aux potos de la BAB. \textcolor{Bittersweet}{Merci Thomas}, astre du Val-de-Marne, empereur de la chimie computationnelle et surtout, hôte de qualité supérieure. Merci d'avoir organisé ces événements réguliers dans ton palais Massicois, auxquel j'ai eu énormément de plaisir à assister. \textcolor{Bittersweet}{Merci Max la Menace} pour ton smile, ta bonne humeur et tout l'amour que tu portes. T'es vraiment un boss, et je suis ultra-heureux que t'aies enfin pu te trouver une thèse ! Plein de bonheur à toi et ta Lulu. \textcolor{Bittersweet}{Merci Jerem}, le D.E.F.R.A.N.C.E, seigneur incontesté dans l'art de la vulgarisation dont le sourire ravageur fait chavirer tous les cœurs. J'ai bien apprécié ces quelques années que l'on a partagé sous le même toit, et je suis heureux que tu t'épanouisses avec ta douce. \textcolor{Bittersweet}{Merci Arthur}, homme fait de muscles, de corne et de sel. Plein de force pour l'ATER, j'espère que tes futurs élèves prendront la mesure de la chance qu'ils ont d'avoir un prof aussi exceptionnel que toi. \textcolor{Bittersweet}{Merci Wassim}, on ne s'est pas beaucoup croisés ces derniers temps (surtout par ma faute), mais t'es un crack. Courage pour ta 4A et tout le bonheur du monde avec le W ! Enfin, un énorme (107 kg au moins) merci à l'étoile du Limousin, au fer de lance de la macroévolution, à cet esprit vif et percutant dont la science a besoin: \textcolor{Bittersweet}{Nilsou}. Je suis hyper heureux de voir nos trajectoires scientifiques converger, et j'ai l'insolence de caresser l'espoir que, peut-être un jour, en plus de te compter parmi mes plus chers amis, je te compterai parmi mes collaborateurs les plus aguerris. En attendant, je languis de voir fleurir le premier @chabrol2027. Merci aussi d'avoir pris le temps de relire mon intro de thèse avec ton regard d'expert en histoire des sciences, et merci pour cette superbe semaine de *co-working* que tu nous as offerte à moi, Thomas et Jerem. Je n'aurais pas pu rêver meilleure mise à l'étrier pour ma rédaction.

\textcolor{Bittersweet}{Merci Raph}, ou plutôt, Dr. Rullan. Ça commence à faire un bail depuis la première année de prépa, quand on sortait dépités des colles de Jubault, ne comprenant pas pourquoi, à productions égales, Clémence sortait avec 4 points de plus que nous... Quel filou ce Marco, n'est-ce pas ? D'ailleurs, en parlant de Marco, force avec le tiens hein, là-dessus on se sait je crois ! Merci pour ces années Lyonnaises, et notamment, ces moments de coloc dans ce chouette petit appart rue Matthieu Varille qu'après 6 ans de bons et loyaux service tu t'apprêtes à rendre. Merci aussi pour ces petits moments passés en ta compagnie ces dernières années, hélas encore trop rares, mais hautement appréciables. Je garderai un très chouette souvenir de ce duo étoilé. Plein de bonheur et de kiff pour ton post-doc en Islande !

\textcolor{Bittersweet}{Merci Hugo (Raveton)}. J'ai passé de très chouettes moments avec toi à Marseille ces dernières années, et je conserverai des souvenirs intarissables de ces scènes que nous avons partagées avec DecheENS. Sans doute les meilleurs concerts de ma vie, sincèrement. Je connais peu de gens avec autant de ressources que toi, et je languis de repasser un peu de temps à tes côtés. Tu es quelqu'un de très inspirant, et je te souhaite le plus grand des épanouissements dans tes projets !

\textcolor{Bittersweet}{Merci Floriane}, la *bioacousti-queen* des primates et des chats ! Sans forcer sur les compliments -- c'est pas mon genre, tu me connais -- à quelques centimètres près t'es pas loin d'être un prototype de ce que les gens s'imaginent quand ils entendent le mot "perfection". Merci pour ces petits moments de papotage et tes visites montpelliéraines toujours bienvenues et bien plus fréquentes que mes visites stéphanoises (je m'en excuse encore). T'es incroyable, sur le plan humain comme scientifique, et sans parler de ce BBL chirurgical. Merci aussi de m'avoir partagé l'info pour la Fyssen et d'avoir été une super source de soutien et de motivation. C'est passé pour toi, pour moi aussi (je sais toujours pas par quel miracle), c'est vraiment incroyable (comme toi) et ça valide une fois de plus ton statut de boss du game. Plein de bonheur pour la suite, et je crois que Francfort-Neûfchatel c'est pas si loin !

\textcolor{Bittersweet}{Merci Bastien (Girault), Loanne, Cara, Fañch, Marie}. On ne s'est pas beaucoup croisés ces derniers temps, mais vous êtes dans mon cœur !

## Ami-es Montpelliérain-es

\textcolor{Bittersweet}{Merci Augustin}. Déjà cinq ans en arrière, fin Avril 2021, je traversais l'Europe en ta compagnie à bord de ton épave roulante, cap sur un Danemark fraîchement déconfiné. Certains appelleraient ça le début d'une belle histoire, mais, pragmatique comme tu es, tu appellerais sûrement ça un trajet comme les autres. Merci pour tous ces moments passés en ta compagnie depuis lors -- avec une mention spéciale à notre nuit improvisée sur les îles Cíes alors que nous avions manqué le bateau censé nous ramener sur le continent (heureusement qu'on a trouvé des bières) ! Je ne me lasserai jamais de ton aplomb comique, de ton côté pince-sans-rire si caractéristique, de ton alcoolisme et de ton appétence (partagée) pour la bonne bouffe. À bien des égards, tu es quelqu'un de très inspirant, et j'espère te garder parmi mes plus proches amis.

\textcolor{Bittersweet}{Merci Simon (Lacombe)}. Je suis heureux de m'être retrouvé à Montpellier à tes côtés, et je garderai la tête pleine de chouettes souvenirs de nos quelques sessions de grimpe, de nos petits verres en terrasse ou à nos domiciles respectifs. Merci aussi pour ces petites bouffées de vert que tu m'as offertes en me laissant t'accompagner à tes terrains. Tu es quelqu'un avec qui j'ai énormément de plaisir à discuter, et je pense que tu fais partie des personnes les plus brillantes que je connaisse. Nul doute que l'avenir qui t'est promu dans le milieu académique sera radieux ! J'en profite aussi pour te remercier, \textcolor{Bittersweet}{Axelle}. Loin de moi l'intention de te réduire à ton statut matrimonial, tu es bien évidemment plus à mes yeux que "la meuf de Simon". Merci pour ces invitations dans votre petit appart *cocooning*, et je suis des plus honorés de m'être vu attribuer le titre de parrain de Crevette, que j'essaye d'honorer du mieux que je peux. Gros cœur sur vous deux (trois?), vous êtes vraiment de chouettes ami-es.

\textcolor{Bittersweet}{Merci Julia}, je pense que dans le top 5 des bretons les plus stylés du Sud de la France, t'es pas cinquième ! Merci notamment de m'avoir initié à la scène *underground* du stand-up montpelliérain, devant laquelle je me suis à maintes reprises délecté, et notamment en voyant s'illustrer un certain \textcolor{Bittersweet}{Cox}, que je remercie par ailleurs pour ses performances. T'es trop cool, plein de bonheur pour la suite !

Merci aux potos du \textcolor{Bittersweet}{CEFE \textit{et al}.}, comme l'avait si bien qualifié l'illustre \textcolor{Bittersweet}{Waki} au cours de son sacre au rang d'empereur incontesté de l'épidémiologie fondamentale. Merci aussi à tous-tes celleux qui faisaient, font et continueront à faire du CEFE le labo d'écologie avec la meilleure ambiance de Montpellier ("du monde" même d'après Jerem), notamment \textcolor{Bittersweet}{Waki, Nico Ponsa, Lisa, Erwan, Laurine, Pablo, Léo, Victoria} (oui t'es pas au CEFE mais MARBEC c'est inclus dans le "*et al*.")\textcolor{Bittersweet}{, Giovanny, Nico Silva, Célian, Maurine, Mathieu} (pareil que pour Victoria) \textcolor{Bittersweet}{, Nico Dibot}. Désolé si j'en oublie, vous êtes tous-tes incroyables.

\textcolor{Bittersweet}{Merci Simon (Roy-Marsiquet)}, le giga-chad des soirées branchées, au cou aussi raide qu'un poteau de rugby et à la mâchoire aussi affûtée qu'un sabre japonais. Très belle rencontre, on remercie le Bast, j'ai passé de super moments en ta compagnie et je te souhaite le meilleur pour la suite gros bg !

## Ami-es d'ailleurs

\textcolor{Bittersweet}{Merci Bastien (Ruaud)} pour ces petites bouffées d'oxygène Gardoises venues égayer mon quotidien Héraultais, que ce soit à l'occasion d'un Jeudi de Nîmes, d'un concert de Mika aux Arènes ou juste d'un petit Prolet en semaine. De manière générale, merci pour ces week-ends, ces soirées et ces après-midi mémorables passés en ta compagnie. Je garderai un souvenir inaltérable de nos premières sorties vélo, rythmées par tes "Nan!" catégoriques à chaque fois que je te demandais si tu passais un bon moment, te plaignant de ton postérieur endolori avant d'expier un râle dont toi seul a le secret. Tu es quelqu'un de vrai avec qui je savoure chaque instant passé, et sans plus faire usage de compliments -- art dans lequel tu sais que j'excelle --, ta personnalité est, par bien des aspects, extrêmement inspirante (si l'on omet ta faible appétence pour les tâches ménagères, et ta forte propension à ne pas te forcer à faire les choses pour lesquelles tu as une faible appétence). Je suis fier de te compter parmi mes amis les plus chers.

\textcolor{Bittersweet}{Merci P.O}, merci ma p'tite caille ! Déjà dix ans que tu es descendu du Nord pour venir inonder le Sud-Ouest de ton charisme et de ta bonne humeur. Avec toi, j'ai des souvenirs émus de mes premières vagues, mes premières cuites et de ces petits-déjeûners que l'on partageait en classe de Première à la boulangerie avant d'aller voir des films nuls à l'Utopia pour les cours de Français. Tu es une personne en or, et j'ai toujours eu un énorme plaisir à passer du temps avec toi. Tu es quelqu'un qui compte énormément pour moi, alors, merci pour tous ces moments passés et ceux à venir ma caille, et promis je viendrai te voir à Brive !

\textcolor{Bittersweet}{Merci Max (Ferrando)}, l'astre du podo-trail et du sabotage. Bien que tu sois au départ l'ami du P.O, je te considère comme un ami à part entière, et je garderai de super souvenirs de ces moments que j'ai passé avec vous deux pendant ma thèse. T'es vraiment un chouette gars, et je te souhaite toute la réussite du monde dans tes projets académico-professionnels. Peut-être que je prendrai un départ sur un ultra avec toi un jour ?

\textcolor{Bittersweet}{Merci Lucas, merci Hugo}, merci les jumeaux. Ça fait plus de la moitié de nos vies que l'on se côtoie en s'appréciant et en se respectant -- même si je passe un peu pour le fou du bus avec ma trajectoire géographico-professionnelle très divergente à la vôtre ! Avec vous, en plus d'avoir en tête de doux souvenirs de nos escapades sportives à base de VTT, basket, tennis et course à pieds (enfin, la course à pieds avec Hugo c'était il y a un moment... avant la prise de masse !), j'ai vécu mes premières bières, mes premières fêtes de villages, mes premières vacances entre amis et mes premières soirées mémorables, alors que nous plantions la tente dans le jardin de (feu) M. Scott. Vous comptez énormément pour moi, et je ne vous remercierai jamais assez pour tous ces chouettes moments passés en votre compagnie, qui ne se sont pas achevés alors que je quittais le cocon pailleton. Je nous souhaite un avenir commun heureux et durable, et j'en profite pour glisser un gros merci à \textcolor{Bittersweet}{Florence et Olivier} pour leus multiples accueils tous aussi chalereux et bienveillants les uns que les autres dans votre petit havre de bonheur girondin.

\textcolor{Bittersweet}{Merci Damien}. Pareil, ça commence à faire un petit bout de temps que je vois ta petite bouille toute soignée et tes biceps saillants. Merci d'être là, merci pour ta sincérité et ton amitié. Je sais que je pourrai toujours compter sur toi, et ça fait du bien. T'es une perle, et je suis heureux quand je vois ta situation qui se pose, tu le mérites. Hâte de remettre à l'épreuve ta mythique descente qui nous a fait en venir à la conclusion que, grand anatomistes que nous sommes, tu n'avais tout simplement pas de foie. Au risque de me répéter avec ce qui a été dit plus haut, toi aussi tu comptes énormément.

\textcolor{Bittersweet}{Merci Sousou}, Dr. Sousou, l'homme dont le sourire méditerranéen efface la mauvaise humeur des personnes âgées venues renouveler leur ordonnance. Je passe toujours des super moments quand t'es là, t'es vraiment un bon ! Que du bonheur avec ta petite Marie, et maintenant j'espère que t'as arrêté d'aller à la montagne en Twingo pour ne pas dépasser ton leasing !

Merci au reste de l'équipe des Bordelais-es chevronné-es, \textcolor{Bittersweet}{Chloé, Manon, Brice, Margot}. Bien que je passe un peu pour le va-nu-pieds de service à côté de vous, je passe également de chouettes moments avec vous, merci pour ça.

\textcolor{Bittersweet}{Merci Floflo}. J'ai toujours énormément plaisir à passer du temps avec toi, et je te souhaite tout le meilleur du monde. 

## Autres

I \textcolor{Bittersweet}{thank you, Lewis}, the best supervisor that I've ever had. Four years ago, I had the immense pleasure to do my Master's thesis on your (and Sara's) side at the University of Vigo. I have learnt a lot over that experience from your programming and organisational skills (and I probably owe you my British written english!). You have always been very proactive in your projects, and thanks to your massive investment, we could eventually publish this nice study about the sensitivity of palaeobiological pipelines to the use of different global plate models in *Methods in Ecology and Evlution*, which is pretty cool. Thank you also for involving me in the early palaeoverse community, I apologise if my investment progressively faded away as my PhD was going on. Hopefully we can keep collaborating in the future! I also greatly appreciate to see you on a yearly basis at the PalAss. All the best for the future, for you and Paloma!

\textcolor{Bittersweet}{Grazzie, Ale}, it's always nice to see you over conferences. You're a very inspiring scientist, and I wish you the best for the future, you and dinosaurs deserve it.

\textcolor{Bittersweet}{Obrigado Oskar and Thiago (F.L.V.B. Rangel)} for accepting to be on board for what promises to be an exciting opportunity for my first post-doctoral experience. I am very impressed to work with scientists like you, and I hope I will fulfill your expectations.

\textcolor{Bittersweet}{I also thank David Nogués Bravo and Ryan R. Germain} for offering me my first experience in the world of research at the Center for Macroecology, Evolution and Climate (CMEC), University of Copenhagen. To be honest, I don't even know if I would have considered the application that I made as a naive, poorly-skilled first year's Master's student if I had received it myself. This experience was highly formative to me and gave me the will to keep going in the world of academia. Also, thank you very much for offering me the opportunity to get involved in this very cool paper about bird functional diversity over the last million years. I was very lucky, and I thank you for that attention.

Merci aussi à ma professeure de SVT de terminale, \textcolor{Bittersweet}{Amandine Lazarini}, qui a énormément nourri mon amour pour les sciences de la vie et de la Terre, et sans qui je n''aurais pas pu rentrer en prépa'aurais pas eu accès à l'entrée en prépa.

I thank all the PBDB contributors for dedicating a significant amount of their time to make such an amount of data accessible.

## Famille

Me voici à présent à la partie de mes remerciements qui me tient le plus à cœur, et sûrement celle qui m'est le moins évident à concevoir. Imaginer un semblant de cohérence dans un contexte familial décousu, dont j'ai pâti et continue à pâtir n'est en effet pas une tâche facile. Je vais donc me cacher derrière vos individualités exceptionnelles, en improvisant un ciment cohésif entre vous dont la réalité ne dépassera pas le cadre de ces lettres.

\textcolor{Bittersweet}{Merci tout d'abord à mes parents}. Dans la mesure où je vous ai dédié cette thèse, je pense ne pas avoir à épiloguer sur l'importance que vous avez à mes yeux. Vous m'avez toujours encouragé à faire ce qui me plaisait, mettant un point d'honneur sur le fait que vous me soutiendriez quoiqu'il arrive. Après votre séparation, vos vies respectives n'ont pas toujours été faciles. Une nouvelle fois, je n'épiloguerai pas, mais je sais d'où je viens, et je ne l'oublierai pas. Je n'oublierai pas non plus que vous avez toujours tout fait pour nous, et tout fait pour que l'on ne sente pas les moments compliqués. \textcolor{Bittersweet}{Merci Maman}. Tu es dévouée, d'une empathie absolument remarquable, et d'une profonde gentillesse -- pour être honnête, je pense que personne n'est étonné de voir que ton bureau soit devenu le *bureau des pleurs* de ton travail. Tu es, et as toujours été un modèle de savoir-être pour moi. \textcolor{Bittersweet}{Merci Papa}. Tu as une force de caractère que j'admire et dont je suis bien incapable de faire preuve, bien que je pense qu'elle te joue parfois des tours. Je persiste à penser que tu aurais des cartes à jouer dans le monde de la politique -- en prenant peut-être des cours de style vestimentaire, mais ne t'inquiètes pas, j'ai des ami-es qui peuvent te faire un relooking ! Merci pour tout, et notamment pour m'avoir fait découvrir le monde de la musique, de la cuisine et du pastis.

Je me réjouis quand je vois que vous avez refait vos vies avec des personnes formidables pour lesquelles j'éprouve énormément d'affection. \textcolor{Bittersweet}{Merci Jean-Marc}. Ça commence à faire un petit bout de temps que tu as fait irruption dans ma vie, tu es et as toujours été quelqu'un de très aimant, tant pour ma mère que pour nous. Je te remercie pour tout le bonheur que tu nous apportes. Je remercie au passage tes deux fils, devenus mes demi-frères bien après nos mises au monde respectives, pratique, surtout quand on a le même âge. Alors, \textcolor{Bittersweet}{merci Lilian et Lucas}. J'ai énormément de chouettes souvenirs avec vous, les derniers en date remontant à pas plus tard que cet hiver à la montagne alors que nous volions les décorations de Noël du village pour orner la location des parents. Merci pour ces moments, et j'espère qu'il y en aura d'autres. Ensuite, \textcolor{Bittersweet}{merci Geneviève}. Même si ça fait un peu moins longtemps, tu apportes beaucoup de bien à mon père, je te vois très aimante et vous avez une belle relation -- sans parler de tes talents de cuisinière absoluments remarquables. Merci pour ça.

\textcolor{Bittersweet}{Merci Carlito}. Effectivement, il va sans dire que, si je parle en "nous" depuis tout-à-l'heure, c'est bien pour faire référence à mon petit frère. La p'tite souris est maintenant devenue un gros rat (je te rassure, pas aussi gros que ceux du Chapitre 2). Si on passe sur le fait que tu as littéralement pris tous les gènes du charisme et de la bogossitude de la fratrie (j'ai pris la barbe et la calvitie perso), tu es quelqu'un de vraiment talentueux, très drôle, et je suis extrêmement fier de voir comment tu évolues. Tu ne peux pas imaginer le bien que ça me fait de voir à quel point les petites mamies raffolent des séances de sport du Carlito, à quel point tes potes sont unanimes pour dire que t'es incroyable et à quel point tu sais te faire aimer. Je suis conscient de la chance que j'ai de pouvoir dire que mon frère est aussi mon ami. Change rien, t'es un boss !

\textcolor{Bittersweet}{Merci Papy Jean}. Étant donné que l'ouïe se fait capricieuse, ce qui, combiné à mes talents d'articulation hors-pair, n'arrange rien au problème, je pense que des remerciements écrits seront très à-propos. Tu as été un grand-père présent, et je t'en remercie. J'ai énormément de bons souvenirs à tes côtés. Il me restera toujours cette citation de toi qui, à table, nous disais "Plus tard, si tu votes à droite, mon esprit viendra te tirer par les pieds dans ton lit". Merci pour tout ce que tu as fait pour nous.

\textcolor{Bittersweet}{Merci Papy et Mnamna}. J'ai la chance d'avoir pu énormément profiter de ma jeunesse avec des grands-parents formidables, profondément aimants et généreux (quand on voit votre fille, on comprend que les chiens ne font pas des chats). Merci beaucoup pour votre présence et votre soutien indéfectible. J'ai énormément de plaisir à passer du temps avec vous, vous comptez énormément pour moi.

\textcolor{Bittersweet}{Merci Tatie, Tonton Pat et Sylvie}. Votre présence est associée à des moments parmi les plus beaux de mon enfance et de mon adolescence. Également, il va sans dire qu'avoir une tante maîtresse de conférences m'a bien aidé à esquisser les contours d'une ambition professionnelle qui ne m'a pas quitté depuis mes 13 ans. Je vous remercie pour tout, et je vous souhaite tout le meilleur du monde.

\textcolor{Bittersweet}{Merci Lolo et Agnès}. Mes tantes que j'aime à voir sur scène comme à l'apéro. Vous êtes des personnes absolument extraordinaires, à l'image de ces petits loulous que vous avez faits ! Merci pour ces moments passés à vos côtés ces derniers temps, à Cazaux, Avignon ou autre. \textcolor{Bittersweet}{Merci aussi à Pascal et David}, les papas de mes cousins, deux individualités également exceptionnelles avec qui j'aime à passer du temps. Merci aussi de m'avoir logé à Lyon quand je passais mes concours en 2019.

\textcolor{Bittersweet}{Merci Paul et Caro}. Vous êtes des amours, et nous avons passé un très agréable moment dans votre petit havre de bonheur catalan.

J'en profite également pour remercier \textcolor{Bittersweet}{Gisèle et André} pour leur hospitalité et ces chouettes moments Adréchois offerts, Colin pour ces chouettes moments passés et ceux à venir, ainsi que \textcolor{Bittersweet}{Robin} pour sa sympathie, sa disponibilité et ses talents de bricoleur absolument remarquables.

Pour finir, ne dérogeant en rien à la règle du "meilleur pour la fin", merci à la personne que j'ai la chance de compter dans ma vie au quotidien, qui me soutient, me supporte, me comprend, me fait rire, pleurer et avec qui je me sens vivant. Ma meilleure amie. \textcolor{Bittersweet}{Merci Florine}. Merci d'être là, d'être sincère et compatissante avec ma désorganisation chronique. Tu n'as pas choisi la facilité avec quelqu'un comme moi, voué à la précarité géographico-professionnelle pour les prochaines années, et je m'en excuse. Néanmoins, je suis très fier de ce que nous construisons. Qui aurait pu prédire le dessein de ce petit feu qui s'allumait timidement dans une rue Lyonnaise il y a presque cinq ans ?

## Je ne remercie pas...

Les politiques d'austérité à l'égard de l'Enseignement Supérieur et la Recherche, en France comme à l'international, au motif d'une absence de perspective de rentabilité court-termiste, en inadéquation absolue avec les enjeux du moment.

Les efforts acharnés des milliardaires d'extrême-droite à la tête de la plupart des grands médias pour diffuser leurs fantasmes xénophobes sur la base d'argumentaires fallacieux et de méthodes insidieuses.

Les Sionistes, qui justifient un génocide sur la base d'arguments religieux et assimilent toute critique de la politique actuelle menée par l'État d'Israël à de l'antisémitisme.

Les cigales, véritables architectes d'une cacophonie permanente habillant le Sud de la France trois mois dans l'année.

Les soirées karaoké et le Roquefort. Aucune justification.


{{< pagebreak >}}

```{=latex}
\includepdf[pages=-, scale=1]{./Fioritures/Wayna_Picchu.pdf}
```

{{< pagebreak >}}

```{=latex}
\includepdf[pages=-, scale=1]{./Fioritures/Appendices.pdf}
```

{{< pagebreak >}}