# Résumé étendu en Français {.unnumbered header-title="Résumé Français"}

Cette section a pour vocation de produire un bilan un tant soit peu intelligible et digeste des circonvolutions intellectuelles autour de l'histoire évolutive des mammifères sud-Américains ayant animé mes trois dernières années, dans la langue de Molière.

## Considérations préliminaires

En premier lieu, une justification s'impose: pourquoi, en tant qu'Européen, s'intéresser à la biodiversité d'un continent si lointain ? Je vous invite pour cela à vous référer à la carte présentée dans la @fig-maps de l'introduction de ce manuscrit. Cette carte représente, à l'actuel, le nombre d'espèces par unité de surface (aussi appelée richesse spécifique) chez les mammifères terrestres (A), les oiseaux non-marins (B) et les amphibiens (C). Un contraste frappant s'impose alors à nous: l'Amérique du Sud se démarque par son immense richesse spécifique, quasiment supérieure à n'importe quelle autre région du globe. En cela, il est coutume de qualifier le continent sud-Américain (et tout particulièrement sa partie tropicale, en première ligne de laquelle se trouve la fameuse forêt Amazonienne, voir @fig-physiography) de *hotspot* (pouvant se traduire par "haut-lieu") de biodiversité [@raven2020]. En réalité, pour une majorité de groupes d'organismes terrestres allant des plantes aux vertébrés en passant par les insectes, il apparaît que les zones les plus riches en espèces du globe sont inféodées à des latitudes tropicales, à savoir, les deux tiers Nord de l'Amérique du Sud, l'Afrique sub-saharienne et l'Asie du Sud-Est[^resum-1]. 

L'origine de ce désequilibre notoire de biodiversité à la surface du globe n'a rien de trivial, et a intrigué des générations de scientifiques depuis les travaux fondateurs d'Alexander von Humboldt [*p*.*ex*., @humboldt1807], d'Alfred Russel Wallace [*p*.*ex*., @wallace1876; @wallace1878] ou encore du célèbre Charles Darwin [*p*.*ex*., @darwin1859]. Cette question peut se décomposer en deux classes de sous-questions. La première porte sur le *pourquoi* évolutif [*e*.*g*., @stebbins1976; @jablonski2006]. Les tropiques sont-elles plus riches en espèces parce que celles-ci s'y éteignent moins facilement qu'à l'extérieur des tropiques (hypothèse du 'musée tropical', où sont 'conservées' les espèces en y perdurant plus longtemps qu'autre part) ? Parce que les lignées y trouvent davantage d'opportunités pour diversifier (hypothèse du 'berceau tropical', où naissent les espèces) ? Les deux à la fois ? La seconde classe de sous-questions visant à expliquer ce patron spatial porte sur le *comment*: quels sont les propriétés propres aux milieux tropicaux qui en font des milieux riches en espèces ? En dépit de sa caractérisation précoce (fin XIXème) et de l'effort de recherche qu'il a suscité [*e*.*g*., @meseguer2020; @mittelbach2007; @schemske2009; @rolland2014; @tietje2022; @quintero2024], ce désequilibre de richesse spécifique latitudinal, souvent nommé gradient latitudinal de diversité, demeure emplein de zones d'ombre, qui en font une thématique de recherche centrale aux domaines de la macroécologie et la macroévolution (d'où né la dénomination barbare de "perspective macro-éco-évolutive" que vous trouverez dans le titre de cette thèse).

[^resum-1]: Cela dit, des différences notoires de richesse spécifique entre ces trois régions sont à reporter avec, en particlier, les diversités Africaines et sud-Amériaines différant grandement, la première étant, pour beaucoup de groupes, bien inférieure à la dernière. Bien que ce patron soulève bien des interrogations, nous ne nous attarderons pas dessus dans le cadre de ce travail. Si toutefois cette question vous intéresse, je ne peux que vous recommander de vous référer à cette étude parue il y a cinq ans, qui en dresse un joli contexte et propose un mécanisme clair pour l'expliquer, faisant usage des mêmes approches que celles utilisées dans le @sec-chap3 de cette thèse: @hagen2021b.

Nous avons alors une première partie de réponse à la question posée initialement: la biodiversité mammalienne sud-américaine est particulièrement intéressante parce qu'elle est riche, plus riche que la plupart des autres régions du globe. Néanmois, les choses deviennent encore plus intriguantes lorsque l'on met en perspective cette biodiversité actuelle avec celle issue des archives fossiles, permettant de reconstituer les faunes du passé. 

Se surimpose à cela le contraste extrêmement marqué entre la biodiversité sud-Américaine actuelle et celle retrouvée dans le registre fossile.

## Éléments de contexte

Amérique du Sud

Macroévol

## Chapitre 1. Comment la perturbation climatique la plus marquée du Cénozoique, la transition Éocène--Oligocene (*ca.* 34 Ma), a-t-elle impacté les faunes mammaliennes endémiques de l'Amérique du Sud?

## Chapitre 2. Parfois c'est la taille qui compte : un décodage quantitatif de la fascinante histoire évolutive des plus gros rongeurs ayant jamais existé

## Chapitre 3. De l'implication du climat dans l'asymmétrie du Grand Échange Faunsistique inter-Américain: apports d'un simulateur de biodiversité

{{< pagebreak >}}

```{=latex}
\includepdf[pages=-, scale=1]{./Fioritures/General_intro.pdf}
```

{{< pagebreak >}}